# Telco Customer Churn
*Copy Right by Jessica Tanuwijaya and Vivi Novela*

## Business Problem Understanding

**Context**  
Perusahaan telekomunikasi (Telco) memiliki tantangan utama berupa Customer Churn, yaitu pelanggan yang berhenti berlangganan layanan dan berpindah ke kompetitor. Dalam industri Telco, biaya untuk mendapatkan pelanggan baru (acquisition) umumnya lebih mahal dibanding mempertahankan pelanggan yang sudah ada, sehingga churn dapat berdampak langsung pada pendapatan bulanan (recurring revenue), biaya marketing, dan target pertumbuhan.

Perusahaan saat ini memiliki data historis pelanggan yang berisi informasi profil pelanggan, jenis layanan yang digunakan, kontrak, metode pembayaran, serta biaya bulanan dan total biaya. Dari data ini, perusahaan ingin memahami pola pelanggan yang churn serta membangun pendekatan yang lebih proaktif untuk mencegah churn.

**Target**  
Target (label) pada dataset: `Churn`  
`Yes` : pelanggan churn (berhenti berlangganan)  
`No`  : pelanggan tidak churn (masih berlangganan)  

**Problem Statement :**

Saat ini, program retensi (misalnya promo diskon, upgrade paket, bonus kuota, atau penawaran kontrak tahunan) sering kali diberikan secara massal atau berdasarkan intuisi, sehingga:

1. Biaya retensi menjadi tidak efisien karena penawaran diberikan ke pelanggan yang sebenarnya tidak berisiko churn.  
2. Tim Customer Success/Retention terlambat menghubungi pelanggan yang benar-benar berisiko churn.  
3. Perusahaan kehilangan peluang untuk memahami faktor utama yang mendorong churn, sehingga strategi pencegahan churn tidak tepat sasaran.  

Akibatnya, churn tetap tinggi, biaya retensi membengkak, dan revenue bulanan berpotensi turun.

**Goals :**

Berdasarkan permasalahan tersebut, perusahaan ingin:

1. Memprediksi pelanggan yang berisiko churn (probabilitas churn) agar tim retensi bisa melakukan tindakan lebih awal dan lebih terarah.  
2. Mengidentifikasi faktor/variabel yang paling memengaruhi churn (driver churn) sehingga perusahaan dapat:  
   - merancang program retensi yang lebih efektif,  
   - melakukan perbaikan produk/layanan,  
   - menyusun kebijakan harga/kontrak yang lebih tepat.  

**Analytic Approach :**

Pendekatan analisis yang akan dilakukan:

1. Exploratory Data Analysis (EDA)
   - Melihat distribusi churn (proporsi churn vs tidak churn).
   - Menganalisis hubungan churn dengan fitur penting (kontrak, tenure, layanan internet, metode pembayaran, monthly charges, dll.).
   - Mengidentifikasi pola pelanggan churn (misalnya churn lebih tinggi pada kontrak bulanan, pelanggan tenure rendah, dll. — akan dibuktikan di EDA).

2. Predictive Modeling (Machine Learning Classification)
   - Membangun model klasifikasi untuk memprediksi Churn (Yes/No) dan menghasilkan probabilitas churn.
   - Output model diarahkan untuk membantu tim bisnis menentukan prioritas pelanggan yang perlu dihubungi (berdasarkan skor risiko).

3. Interpretability / Insight
   - Menentukan fitur yang paling berkontribusi terhadap churn (feature importance / SHAP).
   - Mengubah hasil model menjadi rekomendasi bisnis yang actionable (siapa ditarget, program retensi apa, dan kenapa).

**Metric Evaluation**

Dalam churn prediction, konsekuensi kesalahan prediksi perlu didefinisikan jelas 

**Definisi Kelas  `Positive`**

Positive class = Churn = Yes (pelanggan yang akan churn)

**Type 1 Error — False Positive (FP)**

Model memprediksi pelanggan akan churn, padahal sebenarnya tidak churn.  
Konsekuensi bisnis:  
- Tim retensi menghabiskan biaya dan effort untuk pelanggan yang tidak perlu ditahan.  
- Promo/insentif terbuang (diskon, voucher, bonus, dll.).  
- Bisa menurunkan margin karena `diskon yang tidak perlu`.

*Estimasi Kerugian Finansial (False Positive)*  
Rata-rata MonthlyCharges pelanggan pada dataset adalah sekitar $65 per bulan.
Jika diasumsikan biaya retensi berupa diskon atau insentif sebesar 20% dari MonthlyCharges, maka:

FP Cost = $65 x 20% = $13 per pelanggan

Artinya, setiap satu kesalahan False Positive diperkirakan menyebabkan pemborosan biaya sekitar $13.

**Type 2 Error — False Negative (FN)**

Model memprediksi pelanggan tidak churn, padahal sebenarnya churn.  
Konsekuensi bisnis:  
- Kehilangan pelanggan yang seharusnya bisa diselamatkan.  
- Kehilangan recurring revenue + potensi biaya akuisisi pelanggan baru.  
- Dampak jangka panjang pada churn rate dan growth.  

**Estimasi Kerugian Finansial (False Negative)**

Jika diasumsikan rata-rata pelanggan yang churn masih memiliki potensi bertahan selama 6 bulan ke depan, maka kehilangan revenue yang terjadi adalah:  

FN Cost = $65 × 6 = $390 per pelanggan  

Apabila ditambahkan estimasi biaya akuisisi pelanggan baru sebesar ±$100, maka total kerugian dapat mencapai:

Total FN Cost ≈ $490 per pelanggan

Dengan demikian, satu False Negative diperkirakan 30–38 kali lebih mahal dibandingkan satu False Positive.

**Cost Consideration (False Negative vs False Positive)**

Dalam konteks bisnis telekomunikasi, kesalahan prediksi churn memiliki dampak biaya yang berbeda antara False Negative (FN) dan False Positive (FP).

False Negative terjadi ketika model memprediksi pelanggan tidak akan churn, tetapi pada kenyataannya pelanggan tersebut benar-benar berhenti menggunakan layanan. Kesalahan ini menyebabkan perusahaan kehilangan pelanggan tanpa sempat melakukan tindakan pencegahan seperti program retensi atau penawaran khusus.

Sebagai ilustrasi sederhana, jika rata-rata pendapatan per pelanggan (Average Revenue Per User / ARPU) adalah sekitar $70 per bulan, maka kehilangan satu pelanggan dapat menyebabkan potensi kehilangan pendapatan sekitar $70 per bulan atau lebih, belum termasuk potensi pendapatan jangka panjang yang hilang.

Sebaliknya, False Positive terjadi ketika model memprediksi pelanggan akan churn, tetapi sebenarnya pelanggan tersebut tidak berniat berhenti berlangganan. Dalam kasus ini perusahaan mungkin memberikan program retensi seperti diskon atau penawaran khusus yang memiliki biaya relatif kecil, misalnya sekitar $10 per pelanggan.

Dengan demikian secara sederhana dapat diasumsikan:  
Cost False Negative = $490  
Cost False Positive = $10  

Dengan demikian, biaya kesalahan False Negative diperkirakan sekitar 49 kali lebih besar dibandingkan False Positive.

Karena biaya kehilangan pelanggan jauh lebih besar dibandingkan biaya memberikan insentif retensi, maka model prediksi churn dalam penelitian ini akan difokuskan pada meminimalkan False Negative.

Oleh karena itu, evaluation metric utama yang digunakan adalah Recall pada kelas churn, karena Recall mengukur kemampuan model dalam menangkap sebanyak mungkin pelanggan yang benar-benar akan churn.

**Prioritas Metric (Rekomendasi)**

Karena kehilangan pelanggan umumnya lebih mahal daripada memberi penawaran yang tidak perlu, maka model sebaiknya fokus mengurangi False Negative (meningkatkan kemampuan menangkap churners).

Berdasarkan estimasi finansial tersebut, karena FN Cost ($390–$490) jauh lebih besar dibandingkan FP Cost ($13), maka secara bisnis False Negative merupakan kesalahan yang lebih merugikan. Oleh karena itu, model difokuskan untuk meminimalkan False Negative dengan meningkatkan Recall (kemampuan menangkap pelanggan yang benar-benar akan churn).

Secara matematis, Recall didefinisikan sebagai:  
Recall = TP / (TP + FN)
dimana:
- `TP (True Positive)` : pelanggan yang benar-benar churn dan berhasil diprediksi churn oleh model  
- `FN (False Negative)` : pelanggan yang sebenarnya churn tetapi diprediksi tidak churn oleh model  

Nilai Recall yang tinggi menunjukkan bahwa model mampu menangkap sebagian besar pelanggan yang benar-benar akan churn, sehingga tim retensi dapat melakukan tindakan lebih awal untuk mencegah kehilangan pelanggan.

**Metric yang paling relevan:**
- Recall (kelas Churn=Yes): seberapa banyak churners yang berhasil terdeteksi.
- Precision (kelas Churn=Yes): seberapa tepat target retensi (agar biaya tidak boros).
- F1-Score (kelas Churn=Yes): kompromi precision & recall.
- PR-AUC (Precision-Recall AUC): sering lebih informatif saat kelas tidak seimbang.
- ROC-AUC: dapat dipakai sebagai pembanding umum.

**Deliverables (Output yang Diharapkan)**

1. Churn Risk Score per pelanggan (probabilitas churn).  
2. Daftar prioritas pelanggan untuk dihubungi tim retensi (misal Top-N berisiko tinggi).  
3. Insight driver churn + rekomendasi aksi:  
   - rekomendasi program retensi berbasis segmen,  
   - rekomendasi perbaikan paket/layanan,  
   - rekomendasi strategi kontrak/harga.  

**Stakeholders (Pihak Terkait)**
- Head of Retention / Customer Success: menentukan strategi follow-up & promo.
- Marketing/CRM Team: menjalankan campaign retensi berbasis target.
- Product Team: memperbaiki produk/layanan yang memicu churn.
- Finance: menilai dampak biaya promo vs penghematan churn.
- Management: memantau churn rate dan dampaknya ke revenue.

**Scope & Assumptions**

Scope (dalam project ini):  
1. Prediksi churn berbasis data historis pelanggan pada dataset.  
2. Fokus pada tindakan preventif/retensi (bukan akuisisi pelanggan baru).

Asumsi:
1. Label churn merepresentasikan kondisi churn pada periode tertentu sesuai pencatatan perusahaan.
2. Model digunakan sebagai alat bantu keputusan (decision support), bukan keputusan final tanpa validasi tim bisnis.
3. Bila tersedia, threshold keputusan (cut-off churn probability) dapat disesuaikan dengan kapasitas tim retensi dan biaya campaign.

## Data Understanding

Data Source : https://www.kaggle.com/datasets/blastchar/telco-customer-churn?resource=download

**Informasi Awal**

Jumlah baris & kolom: 7,043 rows dan 21 columns  
Unit analisis: 1 baris = 1 pelanggan (berdasarkan customerID)  
Catatan penting: dataset tidak mencantumkan periode waktu spesifik pengambilan data (tidak ada kolom tanggal). Analisis dianggap sebagai snapshot historis.

| Attribute        | Data Type, Length | Description                                                          |
| ---------------- | ----------------- | -------------------------------------------------------------------- |
| customerID       | Text              | ID unik untuk setiap pelanggan                                       |
| gender           | Text              | Jenis kelamin pelanggan                                              |
| SeniorCitizen    | Bolean            | Indikator apakah pelanggan termasuk lansia (1 = Ya, 0 = Tidak)       |
| Partner          | Text              | Menunjukkan apakah pelanggan memiliki pasangan                       |
| Dependents       | Text              | Menunjukkan apakah pelanggan memiliki tanggungan                     |
| tenure           | Integer           | Jumlah bulan pelanggan telah berlangganan                            |
| PhoneService     | Text              | Menunjukkan apakah pelanggan menggunakan layanan telepon             |
| MultipleLines    | Text              | Menunjukkan apakah pelanggan memiliki lebih dari satu jalur telepon  |
| InternetService  | Text              | Jenis layanan internet yang digunakan pelanggan                      |
| OnlineSecurity   | Text              | Menunjukkan apakah pelanggan memiliki layanan keamanan online        |
| OnlineBackup     | Text              | Menunjukkan apakah pelanggan memiliki layanan backup online          |
| DeviceProtection | Text              | Menunjukkan apakah pelanggan memiliki layanan perlindungan perangkat |
| TechSupport      | Text              | Menunjukkan apakah pelanggan memiliki layanan dukungan teknis        |
| StreamingTV      | Text              | Menunjukkan apakah pelanggan berlangganan layanan streaming TV       |
| StreamingMovies  | Text              | Menunjukkan apakah pelanggan berlangganan layanan streaming movies   |
| Contract         | Text              | Jenis kontrak pelanggan                                              |
| PaperlessBilling | Text              | Menunjukkan apakah pelanggan menggunakan tagihan tanpa kertas        |
| PaymentMethod    | Text              | Metode pembayaran yang digunakan pelanggan                           |
| MonthlyCharges   | Float             | Biaya yang dibebankan kepada pelanggan setiap bulan                  |
| TotalCharges     | Float             | Total biaya kumulatif yang telah dibayarkan pelanggan                |
| Churn            | Text              | Target: Yes = pelanggan churn, No = pelanggan tidak churn            |

**Penjelasan Tambahan**

**Tipe Internet**
1. Teknologi
 - DSL (Digital Subscriber Line) → Menggunakan kabel telepon tembaga yang sudah ada.
 - Fiber Optic → Menggunakan kabel serat kaca yang mentransmisikan data dalam bentuk cahaya.

2. Kecepatan
 - DSL → Lebih lambat, biasanya sampai ±100 Mbps (tergantung jarak dari sentral).
 - Fiber Optic → Jauh lebih cepat, bisa mencapai ratusan Mbps hingga Gbps.

3. Stabilitas
 - DSL → Kecepatan bisa turun jika jarak rumah jauh dari jaringan.
 - Fiber Optic → Lebih stabil dan tidak terpengaruh jarak secara signifikan.

4. Kualitas Koneksi
 - DSL → Rentan gangguan listrik & cuaca
 - Fiber → Lebih tahan gangguan

5. Pengalaman Penggunaan
 - DSL biasanya cukup untuk: Browsing, Email, Penggunaan ringan
 - Fiber lebih cocok untuk: Streaming, Gaming, Work from home, Upload besar

**Payment Method**
1. Electronic Check (e-check)
Ini adalah pembayaran seperti cek, tetapi dilakukan secara digital → Uang ditarik langsung dari rekening bank tanpa perlu kirim kertas. (Sederhananya: Transfer dari rekening bank, tapi prosesnya seperti sistem cek).

2. Mailed Check
Ini adalah cek dalam bentuk kertas fisik yang:
- Ditulis oleh pelanggan
- Lalu dikirim lewat pos ke perusahaan
(Sederhananya: Tulis cek → kirim lewat surat → perusahaan mencairkan)

In [94]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Patch
from scipy.stats import spearmanr
from scipy.stats import chi2_contingency

# Preprocessing
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.model_selection import StratifiedKFold, cross_validate

# Modeling
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import make_scorer

# Evaluation metrics
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    recall_score,
    precision_score,
    f1_score,
    ConfusionMatrixDisplay,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    average_precision_score,
    make_scorer
)

from sklearn.metrics import (
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    confusion_matrix,
    classification_report
)

# Imbalanced learning
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

# Optional models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# Ignore warnings (opsional)
import warnings
warnings.filterwarnings("ignore")

# Display settings (opsional)
pd.set_option("display.max_columns", None)

In [95]:
#Load Dataset
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes


In [96]:
print("Shape (rows, cols):", df.shape)
display(df.sample(5, random_state=42))

df.info()

Shape (rows, cols): (7043, 21)


,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.8,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.7,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,No,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.1,No


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


## Data Cleaning

Pada tahap ini, akan dilakukan pembersihan terhadap dataset Telco Customer Churn agar siap digunakan untuk analisis dan pembuatan model machine learning. Fokus utama cleaning adalah:  
1. Mengecek ringkasan kualitas data (tipe data, missing value, unique value) per kolom  
2. Menghapus kolom yang tidak relevan untuk modeling (identifier)  
3. Memperbaiki kolom yang salah tipe data (khususnya TotalCharges)  
4. Menstandarkan kategori tertentu agar lebih konsisten (opsional tapi bagus untuk modeling)  

In [97]:
listItem = []
for col in df.columns:
    listItem.append([
        col,
        df[col].dtype,
        df[col].isna().sum(),
        round((df[col].isna().sum()/len(df[col])) * 100, 2),
        df[col].nunique(),
        list(df[col].drop_duplicates().sample(min(2, df[col].nunique()), random_state=42).values)
    ])

dfDesc = pd.DataFrame(
    columns=["dataFeatures", "dataType", "null", "nullPct", "unique", "uniqueSample"],
    data=listItem
)

dfDesc

,dataFeatures,dataType,null,nullPct,unique,uniqueSample
0,customerID,object,0,0.0,7043,"[1024-GUALD, 0484-JPBRU]"
1,gender,object,0,0.0,2,"[Male, Female]"
2,SeniorCitizen,int64,0,0.0,2,"[1, 0]"
3,Partner,object,0,0.0,2,"[No, Yes]"
4,Dependents,object,0,0.0,2,"[Yes, No]"
5,tenure,int64,0,0.0,73,"[8, 40]"
6,PhoneService,object,0,0.0,2,"[Yes, No]"
7,MultipleLines,object,0,0.0,3,"[No phone service, No]"
8,InternetService,object,0,0.0,3,"[DSL, Fiber optic]"
9,OnlineSecurity,object,0,0.0,3,"[No, Yes]"


Berdasarkan hasil diatas dapat disimpulkan beberapa hal penting terkait kualitas dan karakteristik dataset Telco Customer Churn.

Pertama, seluruh kolom pada dataset memiliki nilai `null = 0` atau `nullPct = 0.0`, yang berarti `tidak terdapat missing value` yang terbaca sebagai `NaN`. Namun demikian, hal ini tidak serta merta menjamin bahwa seluruh data bersih, karena masih dimungkinkan adanya nilai kosong dalam bentuk string (contohnya pada kolom `TotalCharges`).

Kedua, kolom `customerID` memiliki jumlah nilai unik (unique = 7043) yang sama dengan jumlah baris data. Hal ini menunjukkan bahwa `customerID` merupakan identifier untuk setiap pelanggan. Oleh karena itu, kolom ini tidak mengandung informasi prediktif dan tidak akan digunakan sebagai fitur pada tahap pemodelan.

Ketiga, sebagian besar fitur pada dataset bertipe kategori (object), seperti `gender`, `Partner`, `Dependents`, `Contract`, `InternetService`, dan `PaymentMethod`. Kondisi ini mengindikasikan bahwa dataset didominasi oleh variabel kategorikal, sehingga pada tahap data preparation diperlukan proses encoding (misalnya One-Hot Encoding) sebelum digunakan dalam model machine learning.

Keempat, kolom `TotalCharges` masih bertipe object dengan jumlah nilai unik yang sangat tinggi (unique = 6531). Padahal, secara definisi `TotalCharges` merupakan nilai numerik (total biaya kumulatif pelanggan). Hal ini mengindikasikan adanya masalah format data, kemungkinan disebabkan oleh nilai kosong dalam bentuk string atau karakter non-numerik. Oleh karena itu, kolom `TotalCharges` perlu dikonversi menjadi numerik dan dilakukan penanganan khusus terhadap nilai yang tidak valid.

Kelima, fitur numerik utama yang tersedia dalam dataset adalah `SeniorCitizen`, `tenure`, dan `MonthlyCharges`. Ketiga fitur ini memiliki potensi kuat dalam menjelaskan perilaku churn, misalnya pelanggan baru (tenure rendah) atau pelanggan dengan biaya bulanan tinggi cenderung memiliki risiko churn yang berbeda dibandingkan pelanggan lainnya.

Terakhir, sebagian besar fitur kategori memiliki kardinalitas rendah (2–4 kategori), seperti `gender` (2 kategori), `Contract` (3 kategori), dan `PaymentMethod` (4 kategori). Kondisi ini relatif ideal untuk proses encoding dan tidak menimbulkan masalah dimensi fitur yang berlebihan.

**Menangani `TotalCharges` yang bertipe object**  
Sesuai dengan penjelasan poin 4 sebelumnya, maka kolom TotalCharges perlu dibersihkan agar bisa dipakai sebagai fitur numerik. Maka sebagai langkah pertama perlu dilakukan pendeteksian nilai kosong berbentuk string.

In [98]:
blank_total = df["TotalCharges"].astype(str).str.strip().eq("")
print("Blank TotalCharges:", blank_total.sum())

df.loc[blank_total, ["tenure", "MonthlyCharges", "TotalCharges"]].head()

Blank TotalCharges: 11


,tenure,MonthlyCharges,TotalCharges
488,0,52.55,
753,0,20.25,
936,0,80.85,
1082,0,25.75,
1340,0,56.05,


Berdasarkan hasil diatas, terdeteksi terdapat `11 baris` pada kolom `TotalCharges` yang berisi nilai kosong dalam bentuk string (blank), meskipun pada pengecekan awal tidak teridentifikasi sebagai missing value (NaN).

Dari sampel yang ditampilkan, terlihat bahwa seluruh baris dengan `TotalCharges` kosong memiliki nilai tenure = 0. Hal ini menunjukkan bahwa pelanggan-pelanggan tersebut merupakan pelanggan baru yang belum memiliki riwayat tagihan kumulatif, sehingga wajar jika nilai `TotalCharges` belum tercatat.

Temuan ini mengonfirmasi bahwa kolom `TotalCharges memang perlu dilakukan pembersihan dan konversi tipe data menjadi numerik` sebelum digunakan dalam analisis dan pemodelan. Selain itu, karena kondisi kosong tersebut memiliki makna bisnis yang jelas (belum ada total biaya), maka nilai TotalCharges untuk pelanggan dengan tenure = 0 dapat diisi dengan 0 pada tahap selanjutnya.

In [99]:
# Konversi TotalCharges menjadi numeric
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"].astype(str).str.strip(),
    errors="coerce"
)

# Cek tipe data setelah konversi
df[["TotalCharges"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   TotalCharges  7032 non-null   float64
dtypes: float64(1)
memory usage: 55.2 KB


Setelah proses konversi, nilai kosong/string tidak valid akan berubah menjadi NaN.
Langkah ini dilakukan untuk memastikan berapa banyak nilai NaN yang muncul setelah konversi.

In [100]:
# Hitung jumlah NaN setelah konversi
nan_totalcharges = df["TotalCharges"].isna().sum()
print("Jumlah NaN pada TotalCharges setelah konversi:", nan_totalcharges)

# Lihat baris-baris yang menjadi NaN
df.loc[df["TotalCharges"].isna(), ["tenure", "MonthlyCharges", "TotalCharges"]].head(10)

Jumlah NaN pada TotalCharges setelah konversi: 11


,tenure,MonthlyCharges,TotalCharges
488,0,52.55,NaN
753,0,20.25,NaN
936,0,80.85,NaN
1082,0,25.75,NaN
1340,0,56.05,NaN
3331,0,19.85,NaN
3826,0,25.35,NaN
4380,0,20.00,NaN
5218,0,19.70,NaN
6670,0,73.35,NaN


Dari hasil sebelumnya, nilai NaN pada `TotalCharges` umumnya terjadi pada pelanggan dengan tenure = 0 (pelanggan baru).  
Secara bisnis, pelanggan dengan `tenure 0` belum memiliki tagihan kumulatif, sehingga nilai `TotalCharges` wajar jika dianggap 0.  
  
Oleh karena itu, strategi handling yang digunakan adalah: Jika `tenure = 0` dan `TotalCharges = NaN`, maka akan diisi menjadi 0.  
Baris tidak dihapus karena memiliki makna bisnis yang jelas (pelanggan baru dengan tenure = 0 belum memiliki akumulasi biaya), sehingga penghapusan data justru akan menghilangkan informasi penting terkait churn pada fase awal pelanggan.

In [101]:
df.loc[df["tenure"] == 0, "TotalCharges"] = df.loc[df["tenure"] == 0, "TotalCharges"].fillna(0)

print("Jumlah NaN TotalCharges setelah handling:", df["TotalCharges"].isna().sum())

Jumlah NaN TotalCharges setelah handling: 0


In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


Pada dataset Telco, beberapa kolom layanan memiliki kategori seperti:  
- `No internet service` pada kolom add-on internet (misalnya `OnlineSecurity`, `TechSupport`, dll.)  
- `No phone servic`e pada kolom `MultipleLines ` 

Sebenernya kategori ini bukan missing value, melainkan menandakan pelanggan tidak berlangganan layanan utama (internet/phone). Namun jika kategori ini dibiarkan, jumlah kategori menjadi lebih banyak dan bisa memperbesar dimensi fitur saat encoding (One-Hot Encoding), tanpa menambah informasi yang signifikan.  

Karena status 'No internet service' sudah direpresentasikan oleh kategori `No`, maka disederhanakan:  
- `No internet service` -> distandarkan menjadi No  
- `No phone service` -> distandarkan menjadi No

In [103]:
internet_addons = [
    "OnlineSecurity", "OnlineBackup", "DeviceProtection",
    "TechSupport", "StreamingTV", "StreamingMovies"
]

print("Sebelum standarisasi:\n")
for col in internet_addons + ["MultipleLines"]:
    print(f"{col}: {df[col].unique()}")

Sebelum standarisasi:

OnlineSecurity: ['No' 'Yes' 'No internet service']
OnlineBackup: ['Yes' 'No' 'No internet service']
DeviceProtection: ['No' 'Yes' 'No internet service']
TechSupport: ['No' 'Yes' 'No internet service']
StreamingTV: ['No' 'Yes' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
MultipleLines: ['No phone service' 'No' 'Yes']


In [104]:
# Standarisasi No internet service
for col in internet_addons:
    df[col] = df[col].replace("No internet service", "No")

# Standarisasi No phone service
df["MultipleLines"] = df["MultipleLines"].replace("No phone service", "No")

print("Sesudah standarisasi:\n")
for col in internet_addons + ["MultipleLines"]:
    print(f"{col}: {df[col].unique()}")

Sesudah standarisasi:

OnlineSecurity: ['No' 'Yes']
OnlineBackup: ['Yes' 'No']
DeviceProtection: ['No' 'Yes']
TechSupport: ['No' 'Yes']
StreamingTV: ['No' 'Yes']
StreamingMovies: ['No' 'Yes']
MultipleLines: ['No' 'Yes']


Kolom `customerID` merupakan identifier untuk setiap pelanggan. Kolom ini tidak memiliki makna prediktif (hanya sebagai penanda), sehingga akan kita tidak gunakan sebagai fitur pada tahap modeling.

Namun, pada praktiknya, `customerID` tetap berguna untuk:  
- tracking pelanggan tertentu  
- menggabungkan hasil prediksi ke data asli  
- audit/debug hasil model.

Karena itu, dataset biasanya dipisahkan menjadi:
- df_clean (data bersih lengkap termasuk customerID untuk referensi)
- X (fitur untuk modeling tanpa customerID).

In [105]:
# Simpan dataset yang sudah dibersihkan (masih ada customerID untuk tracking)
df_clean = df.copy()

# Pemisahan fitur dan target untuk modeling
target = "Churn"
id_col = "customerID"

X = df_clean.drop(columns=[target, id_col])
y = df_clean[target].map({"No": 0, "Yes": 1})  # 1 = churn (positive class)

print("Shape X:", X.shape)
print("Shape y:", y.shape)
y.value_counts()

Shape X: (7043, 19)
Shape y: (7043,)


Churn
0    5174
1    1869
Name: count, dtype: int64

Distribusi target menunjukkan ketidakseimbangan kelas (churn sekitar 26.5%), sehingga pada tahap modeling perlu dipertimbangkan teknik penanganan imbalanced data seperti oversampling atau penalized model.

Pada dataset ini, `MonthlyCharges` dan `TotalCharges` adalah fitur numerik utama yang merepresentasikan aspek biaya pelanggan. Tahap ini dilakukan untuk memastikan:
- Tidak ada nilai yang tidak masuk akal (misal nilai negatif)
- Distribusi data masih wajar dan tidak ada outlier ekstrem yang berpotensi mengganggu model

In [106]:
num_check_cols = ["MonthlyCharges", "TotalCharges", "tenure"]

display(df_clean[num_check_cols].describe())

# cek nilai negatif (harusnya tidak ada)
for col in ["MonthlyCharges", "TotalCharges"]:
    print(col, "nilai negatif:", (df_clean[col] < 0).sum())

,MonthlyCharges,TotalCharges,tenure
count,7043.000000,7043.000000,7043.000000
mean,64.761692,2279.734304,32.371149
std,30.090047,2266.794470,24.559481
min,18.250000,0.000000,0.000000
25%,35.500000,398.550000,9.000000
50%,70.350000,1394.550000,29.000000
75%,89.850000,3786.600000,55.000000
max,118.750000,8684.800000,72.000000


MonthlyCharges nilai negatif: 0
TotalCharges nilai negatif: 0


Artinya, tidak ada nilai biaya yang tidak logis (misalnya biaya minus), sehingga data numerik berada pada kondisi yang wajar untuk dianalisis.

In [107]:
def iqr_outlier_summary(data, col):
    q1 = data[col].quantile(0.25)
    q3 = data[col].quantile(0.75)
    iqr = q3 - q1
    
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    
    outlier_mask = (data[col] < lower) | (data[col] > upper)
    outlier_count = outlier_mask.sum()
    outlier_pct = outlier_count / len(data) * 100
    
    return pd.Series({
        "Q1": q1,
        "Q3": q3,
        "IQR": iqr,
        "LowerBound": lower,
        "UpperBound": upper,
        "OutlierCount": int(outlier_count),
        "OutlierPct(%)": round(outlier_pct, 2)
    })

outlier_monthly = iqr_outlier_summary(df_clean, "MonthlyCharges")
outlier_total = iqr_outlier_summary(df_clean, "TotalCharges")

display(pd.DataFrame([outlier_monthly, outlier_total], index=["MonthlyCharges", "TotalCharges"]))

,Q1,Q3,IQR,LowerBound,UpperBound,OutlierCount,OutlierPct(%)
MonthlyCharges,35.50,89.85,54.35,-46.025,171.375,0.0,0.0
TotalCharges,398.55,3786.60,3388.05,-4683.525,8868.675,0.0,0.0


Karena rentang batas IQR menghasilkan nilai batas bawah yang negatif (yang secara praktis tidak mungkin terjadi untuk biaya), dan seluruh data masih berada dalam batas atas-bawah tersebut, maka tidak terdeteksi outlier pada variabel `MonthlyCharges` maupun `TotalCharges`.

Berdasarkan hasil perhitungan IQR sebelumnya, tidak ditemukan outlier pada variabel MonthlyCharges maupun TotalCharges. Untuk memastikan kembali, dilakukan pemeriksaan visual menggunakan boxplot, scatterplot, dan histogram.

In [108]:
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.boxplot(y=df_clean["MonthlyCharges"])
plt.title("Boxplot - MonthlyCharges")

plt.subplot(1,2,2)
sns.boxplot(y=df_clean["TotalCharges"])
plt.title("Boxplot - TotalCharges")

plt.tight_layout()
plt.show()

Dari boxplot terlihat bahwa:
- Tidak terdapat titik yang berada di luar whisker.
- Seluruh data berada dalam batas bawah dan batas atas IQR.
- Nilai MonthlyCharges berada dalam rentang ±18 hingga ±120.
- Nilai TotalCharges berada dalam rentang ±0 hingga ±8800.

Hal ini mengonfirmasi bahwa tidak terdapat nilai ekstrem yang menyimpang secara signifikan.

In [109]:
plt.figure(figsize=(6,5))
plt.scatter(df_clean["MonthlyCharges"], df_clean["TotalCharges"], alpha=0.3)
plt.xlabel("MonthlyCharges")
plt.ylabel("TotalCharges")
plt.title("Scatterplot: MonthlyCharges vs TotalCharges")
plt.show()

Scatterplot menunjukkan pola hubungan yang logis dan terstruktur:
- Terlihat pola linear meningkat, yang wajar karena TotalCharges merupakan akumulasi dari MonthlyCharges seiring waktu (tenure).
- Tidak terdapat titik yang terpisah jauh dari kumpulan data utama.
- Tidak ditemukan anomali atau nilai yang menyimpang drastis.

Pola ini menunjukkan hubungan yang konsisten antar variabel dan tidak mengindikasikan adanya outlier multivariat.

Pola linear ini mengindikasikan adanya korelasi kuat antara tenure dan TotalCharges, sehingga perlu diperhatikan potensi multikolinearitas pada model linear seperti Logistic Regression.

In [110]:
plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
sns.histplot(df_clean["MonthlyCharges"], bins=30, kde=True)
plt.title("Distribution - MonthlyCharges")

plt.subplot(1,2,2)
sns.histplot(df_clean["TotalCharges"], bins=30, kde=True)
plt.title("Distribution - TotalCharges")

plt.tight_layout()
plt.show()

Distribusi MonthlyCharges:
- Menunjukkan dua cluster utama (low-tier dan high-tier pricing).
- Tidak terdapat lonjakan ekstrem yang terisolasi.

Distribusi TotalCharges:
- Cenderung right-skewed (miring ke kanan), yang wajar karena sebagian pelanggan memiliki tenure panjang sehingga akumulasi biaya lebih besar.
- Tidak terlihat nilai ekstrem yang berdiri sendiri.

**Kesimpulan**  
Tidak terdapat outlier signifikan pada variabel numerik utama (MonthlyCharges dan TotalCharges). Data berada dalam rentang yang wajar dan tidak memerlukan perlakuan khusus seperti trimming atau winsorizing.  
Keputusan ini diambil karena tidak ditemukan outlier ekstrem baik secara statistik (IQR method) maupun secara visual (boxplot dan scatterplot), sehingga tidak dilakukan trimming atau winsorizing agar distribusi asli data tetap terjaga dan tidak menghilangkan variasi alami pelanggan.

## Analysis Data

### Understanding Our Customer and Business Condition

In [111]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
count,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.162147,32.371149,64.761692,2279.734304
std,0.368612,24.559481,30.090047,2266.794470
min,0.000000,0.000000,18.250000,0.000000
25%,0.000000,9.000000,35.500000,398.550000
50%,0.000000,29.000000,70.350000,1394.550000
75%,0.000000,55.000000,89.850000,3786.600000
max,1.000000,72.000000,118.750000,8684.800000


In [112]:
df.describe(include='object')

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,2,3,2,2,2,2,2,2,3,2,4,2
top,3186-AJIEK,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,No
freq,1,3555,3641,4933,6361,4072,3096,5024,4614,4621,4999,4336,4311,3875,4171,2365,5174


In [113]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
display(df.head())

# Churn proportion
churn_counts = df["Churn"].value_counts()
churn_pct = df["Churn"].value_counts(normalize=True) * 100

print("\nChurn distribution:")
display(pd.DataFrame({"count": churn_counts, "pct(%)": churn_pct.round(2)}))

Rows: 7043
Columns: 21


,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes



Churn distribution:


,count,pct(%)
Churn,,
No,5174,73.46
Yes,1869,26.54


Dataset terdiri dari 7.043 pelanggan dengan total 21 fitur yang mencakup profil demografis, jenis layanan, kontrak, metode pembayaran, serta informasi biaya bulanan dan total biaya.

Distribusi label menunjukkan bahwa:
- 73.46% pelanggan tidak churn
- 26.54% pelanggan churn

Hal ini mengindikasikan adanya class imbalance, di mana kelas "No Churn" lebih dominan dibandingkan "Churn"

#### Customer Proportion by Gender

In [114]:
labels = ['Female', 'Male']
jumlah_pelanggan = [(df['gender'] == 'Female').sum(), (df['gender'] == 'Male').sum()]

plt.figure(figsize=(6,6))
plt.pie(
    jumlah_pelanggan,
    labels=labels,
    autopct=lambda p: '{:.1f}%\n({:.0f})'.format(p, p*sum(jumlah_pelanggan)/100),
    startangle=90,
    wedgeprops={'edgecolor':'black'},
    textprops={'fontsize':10, 'color':'black','fontweight':'bold'},
    colors=['#4A90E2', '#1F4E79'],
)
plt.title('Customer Proportion by Gender', fontweight='bold')
plt.show()

Proporsi pelanggan laki-laki dan perempuan terlihat hampir seimbang. Namun, pelanggan masih sedikit didominasi oleh laki-laki sebanyak 3.555 orang (50,5%), sedangkan pelanggan perempuan berjumlah 3.488 pelanggan (49,5%).

#### Customer Demographics by Gender

In [115]:
# Kolom demografi
features = ['SeniorCitizen', 'Partner', 'Dependents']

# Warna berdasarkan gender (Yes, No)
gender_colors = {
    'Female': ("#7C4BCA", "#D3C5F6"),
    'Male': ("#1F4E79","#9DC3E6")
}

# PREPARE DATA
rows = []

for col in features:

    for gender in ['Female','Male']:

        df_g = df[df['gender']==gender]

        if col == 'SeniorCitizen':
            yes = (df_g[col]==1).sum()
        else:
            yes = (df_g[col]=='Yes').sum()

        total = len(df_g)

        rows.append({
            "Feature": col,
            "Gender": gender,
            "Yes": yes,
            "No": total-yes,
            "Yes_pct": yes/total*100
        })

plot_df = pd.DataFrame(rows)

# PLOT
x = np.arange(len(features))
width = 0.35

plt.figure(figsize=(12,6))

for i, gender in enumerate(['Female','Male']):

    sub = plot_df[plot_df.Gender==gender]
    pos = x + (i-0.5)*width

    yes_color, no_color = gender_colors[gender]

    # YES BAR
    plt.bar(pos, sub.Yes_pct, width,
            color=yes_color)

    # NO BAR
    plt.bar(pos, 100-sub.Yes_pct, width,
            bottom=sub.Yes_pct,
            color=no_color)

    # TEXT LABEL
    for j, row in sub.reset_index().iterrows():

        plt.text(pos[j], row.Yes_pct/2,
                 f"{row.Yes_pct:.1f}%\n({row.Yes})",
                 ha="center", va="center",
                 color="white", fontsize=9, fontweight="bold")

        plt.text(pos[j], row.Yes_pct+(100-row.Yes_pct)/2,
                 f"{100-row.Yes_pct:.1f}%\n({row.No})",
                 ha="center", va="center",
                 color="black", fontsize=9, fontweight="bold")

# X LABELS
xticks = []
labels = []

for i in range(len(features)):
    xticks += [x[i]-width/2, x[i]+width/2]
    labels += ["Female","Male"]

plt.xticks(xticks, labels)

# Label fitur utama
for i,f in enumerate(features):
    plt.text(x[i], -8, f, ha="center", fontsize=11, fontweight="bold")

plt.ylabel("Percentage (%)")
plt.title("Customer Demographics by Gender", fontweight='bold')
plt.ylim(0,105)

legend_elements = [
    Patch(facecolor="#7C4BCA", label="Female - Yes"),
    Patch(facecolor="#D3C5F6", label="Female - No"),
    Patch(facecolor='#1F4E79', label="Male - Yes"),
    Patch(facecolor='#9DC3E6', label="Male - No")]

plt.legend(handles=legend_elements, title="Category",loc="upper left", bbox_to_anchor=(1.02, 1))
plt.tight_layout()
plt.show()

Berdasarkan grafik diatas maka:
- Proporsi pelanggan didominasi oleh pelanggan anak muda dibandingkan pelanggan senior relatif kecil baik pada perempuan maupun laki-laki. 
  - Pelanggan senior perempuan sebanyak 568 orang (16.3%) dan pelanggan anak muda perempuan sebanyak 2.920 orang (83,7%).
  - pelanggan senior laki-laki sebanyak 574 orang (16.1%) dan pelanggan anak muda laki-laki sebanyak 2.981 orang (83,9%).
- Proporsi pelanggan yang belum memiliki pasangan (partner) sedikit lebih banyak daripada pelanggan yang sudah memiliki pasangan.
  - Pelanggan Perempuan yang sudah memiliki pasangan sebanyak 1.688 orang (48.4%) dan pelanggan perempuan yang belum memiliki pasangan sebanyak 1.800 orang (51.6%).
  - Pelanggan laki-laki yang sudah memiliki pasangan sebanyak 1.714 orang (48.2%) dan pelanggan laki-laki yang belum memiliki pasangan sebanyak 1.841 orang (51.8%).
- Proporsi pelanggan didominasi oleh pelanggan yang tidak memiliki tanggungan.
  - Pelanggan perempuan yang sudah memiliki tanggungan sebanyak 1.028 orang (29.5%) dan pelanggan perempuan yang belum memiliki tanggungan sebanyak 2.460 orang (70.5%)
  - Pelanggan laki-laki yang sudah memiliki tanggungan sebanyak 1.082 orang (30.4%) dan pelanggan laki-laki yang belum memiliki tanggungan sebanyak 2.473 orang (69.6%)

Secara umum, pola demografi antara pelanggan laki-laki dan perempuan terlihat hampir seimbang, tidak ada perbedaan yang signifikan pada status senior, kepemilikan pasangan, maupun tanggungan.

Meskipun secara distribusi demografi terlihat relatif seimbang antara laki-laki dan perempuan, analisis ini belum menunjukkan apakah terdapat perbedaan tingkat churn pada masing-masing segmen. Oleh karena itu, pada tahap analisis selanjutnya perlu dilihat churn rate berdasarkan SeniorCitizen, Partner, dan Dependents untuk mengetahui apakah faktor sosial tersebut berkontribusi terhadap risiko pelanggan berhenti berlangganan.

Hal ini penting karena jika terdapat segmen demografi tertentu dengan churn rate lebih tinggi, maka model prediksi perlu memastikan segmen tersebut dapat terdeteksi dengan baik untuk meminimalkan False Negative dan meningkatkan Recall pada kelas churn.

Secara umum, faktor demografi biasanya bukan pendorong utama churn dalam industri Telco dibandingkan faktor kontrak, tenure, dan biaya layanan, sehingga variabel-variabel tersebut akan menjadi fokus utama pada analisis berikutnya.

#### Customer Tenure Distribution

In [116]:
plt.figure(figsize=(8,5))
bins = np.arange(0, 73, 6)
labelss = ['0-6', '7-12', '13-18', '19-24','25-30', '31-36','37-42', '43-48','49-54', '55-60','61-66','67-72']

bars = sns.histplot(df['tenure'], kde=True)

# Teks diatas bar
for bar in bars.patches:
    height = bar.get_height()
    bars.text(
        bar.get_x() + bar.get_width()/2,
        height,
        int(height),
        ha='center',
        va='bottom',
        fontsize=12,
        fontweight='bold'
    )
midpoints = (bins[:-1] + bins[1:])/2
plt.xticks(midpoints, labelss)
plt.title('Customer Tenure Distribution', fontweight='bold')
plt.xlabel('Tenure')
plt.ylabel('Count of Customer')
plt.tight_layout()
plt.show()

Pada grafik tersebut mmenunjukkan bahwa distribusi pelanggan berdasarkan lama berlangganan (tenure) didominasi oleh pelanggan dengan masa berlangganan yang masih sangat baru, yaitu pada rentang 0–6 bulan sebanyak 1.371 pelanggan. Jumlah pelanggan kemudian menurun secara bertahap pada rentang tenure menengah, dengan titik terendah berada pada periode 37–42 bulan sebanyak 364 pelanggan.
Menariknya, jumlah pelanggan kembali meningkat pada kelompok tenure yang lebih lama, terutama pada rentang 67–72 bulan yang mencapai 1.033 pelanggan. Pola grafik ini membentuk ini membentuk distribusi seperti huruf U, yang menunjukkan bahwa pelanggan cenderung terkonsentrasi pada dua kelompok utama:
- pelanggan baru yang rentang tenure 0-6 bulan dan
- pelanggan yang sudah sangat lama berlangganan yaitu rentang tenure 67-72 bulan.
Walaupun begitu, Pelanggan masih sangat didominasi oleh pelanggan baru, yaitu rentang tenur 0-6 bulan dibandingkan pelanggan dengan rentang tenur 67-72 bulan.

#### Correlation between Tenure and MonthlyCharges

In [117]:
# Hitung Spearman
corr, p_value = spearmanr(df['tenure'], df['MonthlyCharges'])

print("Spearman Correlation:", corr)
print("p-value:", p_value)

# Scatterplot
plt.figure(figsize=(8,6))

sns.scatterplot(
    x=df['tenure'],
    y=df['MonthlyCharges'],
    alpha=0.4
)

# Tambahkan garis trend (regression line)
sns.regplot(
    x=df['tenure'],
    y=df['MonthlyCharges'],
    scatter=False,
    color='red'
)

plt.title(f"Scatterplot Tenure vs Monthly Charges\nSpearman r = {corr:.3f}, p = {p_value:.4f}")
plt.xlabel("Tenure (Months)")
plt.ylabel("Monthly Charges")
plt.tight_layout()
plt.show()

Spearman Correlation: 0.27641678933130215
p-value: 1.0271266876409408e-123


Hipotesis (α = 0.05):
- H0 (Null Hypothesis): Tidak ada hubungan antara Tenure dan MonthlyCharged.
- H1 (Alternative Hypothesis): Ada hubungan antara Tenure dan MonthlyCharged.

Berdasarkan hasil uji Spearman didapatkan nilai p-value = 1.027e-123, dimana nilai p-value < 0.05.

Hasil hipotesis adalah menolak H0, yaitu Tenure memiliki hubungan signifikan terhadap MonthlyCharged. Artinya, semakin lama pelanggan berlangganan, cenderung terjadi peningkatan biaya bulanan. Namun karena nilai Spearman Correlation hanya 0.276, kekuatan hubungan tersebut tergolong lemah, artinya memang semakin lama pelanggan berlangganan, biaya langganan cenderung lebih mahal, tetapi tidak semua pelanggan pasti seperti itu. Itulah kenapa red line cukup melandai.

#### Customer Adoption of Service

In [118]:
all_services = ['PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies']

total_customers = df.shape[0]

yes_percent = []
no_percent = []
yes_counts = []
no_counts = []

for service in all_services:
    
    if service == 'InternetService':
        yes_count = df[df['InternetService'].isin(['DSL','Fiber optic'])].shape[0]
    else:
        yes_count = df[df[service] == 'Yes'].shape[0]
    
    no_count = total_customers - yes_count
    
    yes_counts.append(yes_count)
    no_counts.append(no_count)
    
    yes_percent.append((yes_count / total_customers) * 100)
    no_percent.append((no_count / total_customers) * 100)


plot_df = pd.DataFrame({'Service': all_services,'Yes_%': yes_percent,'No_%': no_percent})


x = np.arange(len(plot_df['Service']))

plt.figure(figsize=(15,6))

# Bar Yes
plt.bar(x, plot_df['Yes_%'], label='Yes', color='#1F4E79')

# Bar No (stacked)
plt.bar(x, plot_df['No_%'],
        bottom=plot_df['Yes_%'],
        label='No',
        color='#9DC3E6')

# Tambahkan tulisan %
for i in range(len(x)):
    #YES
    plt.text(i,
             plot_df['Yes_%'][i] / 2,
             f"{plot_df['Yes_%'][i]:.1f}%\n({yes_counts[i]})",
             fontsize=10,
             ha='center',
             va='center',
             color='white',
             fontweight='bold')
    
    #NO
    plt.text(i,
             plot_df['Yes_%'][i] + plot_df['No_%'][i] / 2,
             f"{plot_df['No_%'][i]:.1f}%\n({no_counts[i]})",
             fontsize=10,
             ha='center',
             va='center',
             color='black',
             fontweight='bold')

plt.xticks(x, plot_df['Service'], rotation=0)
plt.ylabel("Percentage of Customers (%)")
plt.title("Customer Adoption of Service", fontweight='bold')
plt.legend()

plt.tight_layout()
plt.show()


Grafik menunjukkan tingkat penggunaan layanan utama oleh pelanggan cukup tinggi.
- Layanan yang paling banyak digunakan adalah Phone Service dengan tingkat penggunaan sebanyak 6.361 pelanggan (90,3%).
- Tingkat penggunaan layanan Internet Service sebanyak 5.517 pelanggan (78,3%).

layanan tambahan didominasi oleh:
- Streaming Movies yaitu sebanyak 2.732 pelanggan (38.8%) dan
- Streaming TV yaitu sebanyak 2.707 pelanggan (38.4%)
penggunaan Layanan tambahan ini hampir sebanyak 45% dari penggunaan keseluruhan Internet Service. 

#### Proportion of Internet Service Types

In [119]:
labels = ['DSL', 'Fiber optic', 'No']
jumlah_pelanggan = [(df['InternetService'] == 'DSL').sum(), (df['InternetService'] == 'Fiber optic').sum(), (df['InternetService'] == 'No').sum()]

plt.figure(figsize=(6,6))
plt.pie(
    jumlah_pelanggan,
    labels=labels,
    autopct=lambda p: '{:.1f}%\n({:.0f})'.format(p, p*sum(jumlah_pelanggan)/100),
    startangle=90,
    wedgeprops={'edgecolor':'black'},
    textprops={'fontsize':10, 'color':'black','fontweight':'bold'},
    colors= ['#4A90E2', '#1F4E79', '#9DC3E6']
)
plt.title('Proportion of Internet Service Types', fontweight='bold')
plt.show()

Grafik menunjukkan bahwa mayoritas pelanggan menggunakan layanan internet tipe Fiber Optic.
- pelanggan menggunakan Layanan Internet tipe Fiber Optic sebanyak 3.096 pelanggan (44,0%).
- Sementara itu, DSL digunakan sebanyak 2.421 pelanggan (34,4%).
- terdapat sekitar 1.526 pelanggan (21,7%) yang tidak menggunakan layanan internet sama sekali.

#### Customers Using Extra Services by Internet Type

In [120]:
iservices = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
             'TechSupport', 'StreamingTV', 'StreamingMovies']

data_plot = []

# Hitung jumlah customer Yes per layanan tambahan
for service in iservices:
    
    temp = (
        df[df[service] == 'Yes']
        .groupby('InternetService')
        .size()
    )
    
    for internet_type in temp.index:
        data_plot.append({
            'InternetService': internet_type,
            'Service': service,
            'Count': temp[internet_type]
        })

plot_df = pd.DataFrame(data_plot)

pivot_df = plot_df.pivot(index='Service',
                         columns='InternetService',
                         values='Count').fillna(0)

# Hitung persentase
pct_df = pivot_df.div(pivot_df.sum(axis=1), axis=0) * 100

# Stacked Bar
ax = pct_df.plot(kind='bar',
                   stacked=True,
                   figsize=(10,6),
                   color=["#1F4E79","#9DC3E6"])

# Label
for i in range(len(pivot_df)):
    bottom = 0
    for col in pct_df.columns:
        pct = pct_df.iloc[i][col]
        val = pivot_df.iloc[i][col]  # tetap ambil jumlah utk label

        if pct > 0:
            ax.text(i,
                bottom + pct/2,
                f'{pct:.1f}%\n({int(val)})',
                ha='center',
                va='center',
                color='black',
                fontweight='bold',
                fontsize=9)
            bottom += pct

plt.xlabel("Service Type")
plt.ylabel("Percentage of Customers (%)")
plt.title("Customers Using Extra Services by Internet Type",
          fontweight='bold')

plt.xticks(rotation=0)
plt.legend(title="Internet Service",loc="upper left", bbox_to_anchor=(1.005, 1))
plt.tight_layout()
plt.show()

Grafik menunjukkan perbandingan jumlah pelanggan berdasarkan jenis layanan tambahan antara pengguna DSL dan Fiber Optic.
1. Pelanggan menggunakan Layanan Internet tipe **Fiber Optic** lebih banyak menggunakan layanan hiburan mengindikasikan bahwa pengguna Fiber Optic cenderung memanfaatkan layanan yang membutuhkan koneksi internet lebih cepat dan stabil.
  - Streaming Movies sebanyak 1.751 pelanggan
  - Streaming TV sebanyak 1.750 pelanggan

2. Sementara itu, pelanggan pelanggan menggunakan layanan Internet tipe **DSL** lebih banyak menggunakan layanan yang bersifat perlindungan dan dukungan teknis, seperti:
  - Online Security sebanyak 1.180 pelanggan
  - Tech Support sebanyak 1.178 pelanggan

#### Customer Distribution by Contract Type

In [121]:
labels1 = ['Month-to-month', 'One year', 'Two year']
kontrak_pelanggan = [(df['Contract'] == 'Month-to-month').sum(), (df['Contract'] == 'One year').sum(), (df['Contract'] == 'Two year').sum()]

plt.figure(figsize=(6,6))
plt.pie(
    kontrak_pelanggan,
    labels=labels1,
    autopct=lambda p: '{:.1f}%\n({:.0f})'.format(p, p*sum(kontrak_pelanggan)/100),
    startangle=90,
    wedgeprops={'edgecolor':'black'},
    textprops={'fontsize':10, 'color':'black','fontweight':'bold'},
    colors= ['#4A90E2', '#1F4E79', '#9DC3E6']
)
plt.title('Customer Distribution by Contract Type', fontweight='bold')
plt.show()

Grafik menunjukkan bahwa mayoritas pelanggan cenderung memilih kontrak jangka pendek dibandingkan kontrak jangka panjang yang menandakan bahwa sebagian besar pelanggan lebih memilih fleksibilitas tanpa komitmen jangka panjang.
- kontrak Month-to-month, yaitu sebanyak 3.875 pelanggan (55%). Hal ini 
- Kontrak dua tahun, yaitu sebanyak 1.695 pelanggan (24,1%)
- Kontrak satu tahun, yaitu sebanyak 1.473 pelanggan (20,9%)

#### PaperlessBilling Adoption

In [122]:
labels2 = ['Yes', 'No']
billing_pelanggan = [(df['PaperlessBilling'] == 'Yes').sum(), (df['PaperlessBilling'] == 'No').sum()]

plt.figure(figsize=(6,6))
plt.pie(
    billing_pelanggan,
    labels=labels2,
    autopct=lambda p: '{:.1f}%\n({:.0f})'.format(p, p*sum(billing_pelanggan)/100),
    startangle=90,
    wedgeprops={'edgecolor':'black'},
    textprops={'fontsize':10, 'color':'black','fontweight':'bold'},
    colors=["#1F4E79","#9DC3E6"]
)
plt.title('PaperlessBilling Adoption', fontweight='bold')
plt.show()

Grafik menunjukkan bahwa sebagian besar pelanggan telah menggunakan paperless billing, yaitu
- Paperless Billing sebanyak 4.171 pelanggan (59,2%).
- Yang masih menggunakan metode penagihan konventional sebanyak 2.872 pelanggan (40.8%)
Secara umum, pelanggan cenderung sudah mulai beralih ke sistem paperless, yang dapat mencerminkan preferensi terhadap kemudahan, efisiensi, dan aksesibilitas dalam pengelolaan tagihan.

#### Customer Distribution by Payment Method

In [123]:
# Jumlah Pelanggan masing-masing Payment Method

payment = df['PaymentMethod'].value_counts()
payment_pct = df['PaymentMethod'].value_counts(normalize=True)*100

plt.figure(figsize=(8,5))
bars = payment.plot(
    kind='bar',
    edgecolor='black'
)

plt.title('Customer Distribution by Payment Method', fontweight='bold')
plt.xlabel('Payment Method')
plt.ylabel('Customer Count')

# tambah nilai angka di atas bar
for i, bar in enumerate(bars.patches):
    height = bar.get_height()
    percent = payment_pct.iloc[i]
    bars.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f'{percent:.1f}%\n({int(height)})',
        ha='center', va='bottom', fontweight='bold'
    )
plt.ylim(0, max(payment) * 1.15)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

Grafik menunjukkan bahwa:
- metode pembayaran Electronic Check adalah metode pembayaran yang paling banyak digunakan pelanggan, yaitu sebanyak 2.365 pelanggan (33.6%).
- metode pembayaran Mailed Check adalah metode pembayaran yang paling banyak digunakan ke dua, yaitu sebanyak 1.612 pelanggan (22.9%).

Maka secara umum, pelanggan lebih banyak menggunakan metode pembayaran manual berbasis cek, khususnya electronic check, dibandingkan metode pembayaran otomatis seperti transfer bank atau kartu kredit.

### Our Customer Churn Rate

#### Customer Churn Rate

In [124]:
labelss = ['Yes', 'No']
churn_pelanggan = [(df['Churn'] == 'Yes').sum(), (df['Churn'] == 'No').sum()]

plt.figure(figsize=(6,6))
plt.pie(
    churn_pelanggan,
    labels=labelss,
    autopct=lambda p: '{:.1f}%\n({:.0f})'.format(p, p*sum(churn_pelanggan)/100),
    startangle=90,
    wedgeprops={'edgecolor':'black'},
    textprops={'fontsize':10, 'color':'black','fontweight':'bold'},
    colors=["#1F4E79","#9DC3E6"]
)
plt.title('Customer Churn Rate', fontweight='bold')
plt.show()

Grafik menunjukkan bahwa:
- sebesar 5.174 pelanggan tidak melakukan churn (73,5%).
- sebesar 1.869 pelanggan yang churn (26,5%).

Hal ini menunjukkan bahwa meskipun mayoritas pelanggan masih bertahan, tingkat churn masih cukup signifikan (sekitar seperempat dari total pelanggan), sehingga tetap perlu menjadi perhatian dalam strategi retensi pelanggan.

#### Churn Distribution by Customer Demographics

In [125]:
features = ['SeniorCitizen', 'Partner', 'Dependents', 'gender']

rows = []

for col in features:
    
    if col == 'SeniorCitizen':
        categories = [0,1]
    else:
        categories = df[col].unique()
    
    for cat in categories:
        
        if col == 'SeniorCitizen':
            subset = df[df[col] == cat]
            label = 'Yes' if cat==1 else 'No'
        else:
            subset = df[df[col] == cat]
            label = cat
        
        total = len(subset)
        
        churn_yes = (subset['Churn']=='Yes').sum()
        churn_no  = (subset['Churn']=='No').sum()
        
        rows.append({
            "Feature": col,
            "Category": label,
            "Churn_Yes_pct": churn_yes/total*100,
            "Churn_No_pct": churn_no/total*100,
            "Churn_Yes": churn_yes,
            "Churn_No": churn_no
        })

plot_df = pd.DataFrame(rows)

# PLOT
plt.figure(figsize=(14,6))

x = np.arange(len(plot_df))
width = 0.6

# NO CHURN BAR
plt.bar(x,
        plot_df['Churn_No_pct'],
        width,
        label='No Churn',
        color="#1F4E79")

# CHURN BAR
plt.bar(x,
        plot_df['Churn_Yes_pct'],
        width,
        bottom=plot_df['Churn_No_pct'],
        label='Churn',
        color="#9DC3E6")

# TEXT ANNOTATION
for i in range(len(plot_df)):
    
    no_pct = plot_df['Churn_No_pct'].iloc[i]
    yes_pct = plot_df['Churn_Yes_pct'].iloc[i]
    
    no_count = plot_df['Churn_No'].iloc[i]
    yes_count = plot_df['Churn_Yes'].iloc[i]

    # NO CHURN TEXT
    plt.text(i,
             no_pct/2,
             f"{no_pct:.1f}%\n({no_count})",
             ha='center',
             va='center',
             color='white',
             fontsize=9,
             fontweight='bold')

    # CHURN TEXT
    plt.text(i,
             no_pct + yes_pct/2,
             f"{yes_pct:.1f}%\n({yes_count})",
             ha='center',
             va='center',
             color='black',
             fontsize=9,
             fontweight='bold')

# AXIS & TITLE
plt.xticks(x,
           plot_df['Feature'] + " - " + plot_df['Category'],
           rotation=0)

plt.ylabel("Percentage (%)")
plt.title("Churn Distribution by Customer Demographics", fontweight='bold')
plt.legend(loc="upper left", bbox_to_anchor=(1.005, 1))

plt.tight_layout()
plt.show()


Grafik menunjukkan bahwa Churn Rate berisiko pada pelanggan seperti:
- Pelanggan senior memiliki tingkat churn lebih tinggi, yaitu sebanyak 476 pelanggan (41,7%)
- Pelanggan yang tidak memiliki pasangan memiliki tingkat churn lebih tinggi, yaitu sebanyak 1.200 pelanggan (33,0%).
- Pelanggan yang tidak memiliki tanggungan memiliki tingkat churn lebih tinggi, yaitu sebanyak 1.543 pelanggan (31,3%).
- Pelanggan perempuan memiliki tingkat churn lebih tinggi, yaitu sebanyak 939 pelanggan (26,9%) walaupun tingkat churn antara laki-laki dan perempuan hampir seimbang.

Secara umum, faktor demografis yang paling berkaitan dengan churn adalah:
- Status senior
- Tidak memiliki pasangan
- Tidak memiliki tanggungan

Ketiga kelompok tersebut menunjukkan kecenderungan churn yang lebih tinggi.

#### Churn Rate Distribution by Contract

In [126]:
cont_table = pd.crosstab(df['Contract'], df['Churn'])

chi2, p, dof, expected = chi2_contingency(cont_table)

print("Chi-square value:", chi2)
print("p-value:", p)

Chi-square value: 1184.5965720837926
p-value: 5.863038300673391e-258


Hipotesis (α = 0.05):
- H0 (Null Hypothesis): Tidak ada hubungan antara Contract dan Churn.
- H1 (Alternative Hypothesis): Ada hubungan antara Contract dan Churn.

Dari hasil uji Chi Squared didapatkan nilai p-value = 5.86e-258, dimana nilai p-value < 0.05.

Hasil hipotesis adalah menolak H0, yaitu Contract memiliki hubungan signifikan terhadap Churn. Dikarenakan nilai p-value mendekati nol maka kemungkinan churn terjadi di setiap kategori Contract karena kebetulan hampir nol.

In [127]:
# Crosstab percentage
contract_pct = pd.crosstab(
    df['Contract'],
    df['Churn'],
    normalize='index'
) * 100

# Crosstab jumlah pelanggan
contract_cnt = pd.crosstab(
    df['Contract'],
    df['Churn']
)

plt.figure(figsize=(10,6))

x = np.arange(len(contract_pct))
width = 0.6

# NO CHURN
plt.bar(x,
        contract_pct['No'],
        width,
        label='No Churn',
        color="#1F4E79")

# CHURN
plt.bar(x,
        contract_pct['Yes'],
        width,
        bottom=contract_pct['No'],
        label='Churn',
        color="#9DC3E6")

# TEXT ANNOTATION
for i in range(len(contract_pct)):
    
    no_pct = contract_pct['No'].iloc[i]
    yes_pct = contract_pct['Yes'].iloc[i]
    
    no_cnt = contract_cnt['No'].iloc[i]
    yes_cnt = contract_cnt['Yes'].iloc[i]

    # NO CHURN TEXT
    plt.text(i,
             no_pct/2,
             f"{no_pct:.1f}%\n({no_cnt})",
             ha='center',
             va='center',
             color='white',
             fontsize=10,
             fontweight='bold')

    # CHURN TEXT
    plt.text(i,
             no_pct + yes_pct/2,
             f"{yes_pct:.1f}%\n({yes_cnt})",
             ha='center',
             va='center',
             color='black',
             fontsize=10,
             fontweight='bold')

# AXIS & TITLE
plt.xticks(x, contract_pct.index, rotation=0)
plt.ylabel("Percentage (%)")
plt.title("Churn Rate by Contract Type", fontweight='bold')
plt.legend(loc="upper left", bbox_to_anchor=(1.005, 1))
plt.tight_layout()
plt.show()


Grafik menunjukkan bahwa jenis kontrak yang paling memiliki risiko churn adalah
- Pelanggan dengan kontrak Month-to-month memiliki tingkat churn paling tinggi, yaitu sebanyak 1.655 pelanggan (42,7%). Ini menunjukkan bahwa pelanggan dengan kontrak fleksibel cenderung lebih mudah berhenti berlangganan.
- Pelanggan dengan kontrak One year memiliki churn yang jauh lebih rendah, yaitu sebanyak 166 pelanggan (11,3%).

Secara umum, semakin panjang durasi kontrak, semakin rendah kemungkinan pelanggan untuk churn.
- Kontrak jangka pendek = risiko churn tinggi
- Kontrak jangka panjang = pelanggan lebih loyal

#### Churn Distribution by Tenure

In [128]:
# Kelompok Tenure
# Buat kelompok tenure per 12 bulan
bins1 = np.arange(0, 73, 6)
labels3 = ['0-6', '7-12', '13-18', '19-24','25-30', '31-36','37-42', '43-48','49-54', '55-60','61-66','67-72']

tenure_group = pd.cut(df['tenure'], bins=bins1, labels=labels3, include_lowest=True)

# Hitung Jumlah dan %
tenure_cnt = pd.crosstab(tenure_group, df['Churn'])
tenure_pct = pd.crosstab(tenure_group, df['Churn'], normalize='index') * 100

# Bar Chart
plt.figure(figsize=(12,6))

x = np.arange(len(tenure_pct))
width = 0.8

# NO 
plt.bar(x,
        tenure_pct['No'],
        width,
        label='No Churn',
        color="#1F4E79")

# CHURN
plt.bar(x,
        tenure_pct['Yes'],
        width,
        bottom=tenure_pct['No'],
        label='Churn',
        color="#9DC3E6")

# TEXT
for i in range(len(tenure_pct)):
    
    no_pct = tenure_pct['No'].iloc[i]
    yes_pct = tenure_pct['Yes'].iloc[i]
    
    no_cnt = tenure_cnt['No'].iloc[i]
    yes_cnt = tenure_cnt['Yes'].iloc[i]

    plt.text(i,
             no_pct/2,
             f"{no_pct:.1f}%\n({no_cnt})",
             ha='center',
             va='center',
             color='white',
             fontsize=9,
             fontweight='bold')

    plt.text(i,
             no_pct + yes_pct/2,
             f"{yes_pct:.1f}%\n({yes_cnt})",
             ha='center',
             va='center',
             color='black',
             fontsize=9,
             fontweight='bold')

plt.xticks(x, tenure_pct.index)
plt.ylabel("Percentage (%)")
plt.title("Churn Distribution by Tenure", fontweight = 'bold')
plt.legend(loc="upper left", bbox_to_anchor=(1.005, 1))

plt.tight_layout()
plt.show()


Grafik menunjukkan bahwa:
- Pelanggan dengan tenure 0–6 bulan memiliki tingkat churn tertinggi, yaitu sebanyak 784 pelanggan (52,9%). Artinya, lebih dari setengah pelanggan baru berisiko berhenti berlangganan.

Seiring bertambahnya masa berlangganan, tingkat churn menurun secara konsisten sampai tingkat Churn terendah ada pada pelanggan dengan tenure sangat lama:
67–72 bulan: sebanyak 50 pelanggan (5,3%)

Secara umum:
- Pelanggan baru memiliki risiko churn paling tinggi
- Semakin lama pelanggan bertahan, semakin kecil kemungkinan mereka churn

#### Churn Rate by Core Services

In [129]:
# Menggunakan Chi Square untuk melihat apakah Internet memiliki hubungan ke tingkat Churn

from scipy.stats import chi2_contingency

cont_table2 = pd.crosstab(df['InternetService'], df['Churn'])

chi2, p, dof, expected = chi2_contingency(cont_table2)

print("Chi-square value:", chi2)
print("p-value:", p)

Chi-square value: 732.309589667794
p-value: 9.571788222840544e-160


In [130]:
features = ['PhoneService', 'MultipleLines', 'InternetService']

rows = []

for col in features:

    grouped = df.groupby(col)['Churn'].value_counts().unstack().fillna(0)
    
    for cat in grouped.index:

        total = grouped.loc[cat].sum()
        churn_yes = grouped.loc[cat].get('Yes',0)
        churn_no  = grouped.loc[cat].get('No',0)

        rows.append({
            "Feature": col,
            "Category": cat,
            "Churn_Yes_pct": churn_yes/total*100,
            "Churn_No_pct": churn_no/total*100,
            "Churn_Yes": churn_yes,
            "Churn_No": churn_no
        })

plot_df = pd.DataFrame(rows)

# PLOT
plt.figure(figsize=(14,6))

x = np.arange(len(plot_df))
width = 0.6

# NO CHURN
plt.bar(x,
        plot_df['Churn_No_pct'],
        width,
        label='No Churn',
        color="#1F4E79")

# CHURN
plt.bar(x,
        plot_df['Churn_Yes_pct'],
        width,
        bottom=plot_df['Churn_No_pct'],
        label='Churn',
        color="#9DC3E6")

# TEXT
for i in range(len(plot_df)):

    no_pct = plot_df['Churn_No_pct'].iloc[i]
    yes_pct = plot_df['Churn_Yes_pct'].iloc[i]

    no_count = plot_df['Churn_No'].iloc[i]
    yes_count = plot_df['Churn_Yes'].iloc[i]

    plt.text(i,
             no_pct/2,
             f"{no_pct:.1f}%\n({no_count})",
             ha='center',
             va='center',
             color='white',
             fontsize=9,
             fontweight='bold')

    plt.text(i,
             no_pct + yes_pct/2,
             f"{yes_pct:.1f}%\n({yes_count})",
             ha='center',
             va='center',
             color='black',
             fontsize=9,
             fontweight='bold')

# AXIS
plt.xticks(x, plot_df['Feature']+ '-' + plot_df['Category'],
           rotation=10)

plt.ylabel("Percentage (%)")
plt.title("Churn Rate by Core Services")
plt.legend(loc="upper left", bbox_to_anchor=(1.005, 1))

plt.tight_layout()
plt.show()

Grafik menunjukkan bahwa:

**Internet Service**
- pelanggan yang menggunakan Internet service tipe Fiber Optic memiliki tingkat churn tertinggi, yaitu sebanyak 1.297 pelanggan (41,9%). Ini menunjukkan bahwa meskipun Fiber Optic adalah layanan modern, tetapi layanan ini merupakan faktor yang paling berpengaruh terhadap churn (berhenti berlangganan).
- Pelanggan dengan DSL memiliki churn yang lebih rendah, yaitu 19,0%, yang mengindikasikan tingkat stabilitas yang lebih baik dibanding Fiber Optic.
- pelanggan yang tidak menggunakan internet sama sekali memiliki churn paling rendah, yaitu hanya 7,4%.

**Phone Service**:
Walaupun pelanggan yang menggunakan Layanan Multiple Lines paling tinggi diantara layanan telepon lainnya yaitu sebanyak 850 pelanggan (28.6%), tetapi Pelanggan dengan atau tanpa Phone Service memiliki tingkat churn yang relatif mirip (sekitar 25–28%), sehingga layanan ini tidak menunjukkan pengaruh besar terhadap churn.

#### Churn Rate by Aditional Internet Services

In [131]:
features1 = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport','StreamingTV', 'StreamingMovies']

rows = []

for col in features1:

    grouped = df.groupby(col)['Churn'].value_counts().unstack().fillna(0)
    
    for cat in grouped.index:

        total = grouped.loc[cat].sum()
        churn_yes = grouped.loc[cat].get('Yes',0)
        churn_no  = grouped.loc[cat].get('No',0)

        rows.append({
            "Feature": col,
            "Category": cat,
            "Churn_Yes_pct": churn_yes/total*100,
            "Churn_No_pct": churn_no/total*100,
            "Churn_Yes": churn_yes,
            "Churn_No": churn_no
        })

plot_df = pd.DataFrame(rows)

# PLOT
plt.figure(figsize=(17,6))

x = np.arange(len(plot_df))
width = 0.6

# NO CHURN
plt.bar(x,
        plot_df['Churn_No_pct'],
        width,
        label='No Churn',
        color="#1F4E79")

# CHURN
plt.bar(x,
        plot_df['Churn_Yes_pct'],
        width,
        bottom=plot_df['Churn_No_pct'],
        label='Churn',
        color="#9DC3E6")

# TEXT
for i in range(len(plot_df)):

    no_pct = plot_df['Churn_No_pct'].iloc[i]
    yes_pct = plot_df['Churn_Yes_pct'].iloc[i]

    no_count = plot_df['Churn_No'].iloc[i]
    yes_count = plot_df['Churn_Yes'].iloc[i]

    plt.text(i,
             no_pct/2,
             f"{no_pct:.1f}%\n({no_count})",
             ha='center',
             va='center',
             color='white',
             fontsize=9,
             fontweight='bold')

    plt.text(i,
             no_pct + yes_pct/2,
             f"{yes_pct:.1f}%\n({yes_count})",
             ha='center',
             va='center',
             color='black',
             fontsize=9,
             fontweight='bold')

# AXIS

labels = [
    f"{f}\n{c}"
    for f, c in zip(plot_df['Feature'], plot_df['Category'])
]

plt.xticks(x, labels, rotation=0)
plt.ylabel("Percentage (%)")
plt.title("Churn Rate by Aditional Internet Services")
plt.legend()

plt.tight_layout()
plt.show()

Grafik menunjukkan bahwa Secara umum,
- Pelanggan yang tidak menggunakan layanan tambahan cenderung memiliki tingkat churn yang lebih tinggi (29% - 41%) dibandingkan pelanggan yang menggunakan layanan tambahan (14% - 30%).
- Pelanggan yang tidak menggunakan layanan tambahan karena tidak berlangganan internet memiliki tingkat churn paling rendah (+/- 7%) dibandingkan dengan pelanggan yang menggunakan layanan tambahan.

#### Churn Rate by Payment Method

In [132]:
# Menggunakan Chi Square untuk melihat apakah Payment Method memiliki hubungan ke tingkat Churn

cont_table1 = pd.crosstab(df['PaymentMethod'], df['Churn'])

chi2, p, dof, expected = chi2_contingency(cont_table1)

print("Chi-square value:", chi2)
print("p-value:", p)

Chi-square value: 648.1423274814
p-value: 3.6823546520097993e-140


Hipotesis (α = 0.05):
- H0 (Null Hypothesis): Tidak ada hubungan antara Payment Method dan Churn.
- H1 (Alternative Hypothesis): Ada hubungan antara Payment Method dan Churn.

Dari hasil uji Chi Squared didapatkan nilai p-value = 3.68e-140, dimana nilai p-value < 0.05.

Hasil hipotesis adalah menolak H0, yaitu Payment Method memiliki hubungan signifikan terhadap Churn. Dikarenakan nilai p-value mendekati nol maka kemungkinan churn terjadi di setiap kategori dalam Payment Method karena kebetulan hampir nol.

In [133]:
# Crosstab percentage
contract_pct = pd.crosstab(
    df['PaymentMethod'],
    df['Churn'],
    normalize='index'
) * 100

# Crosstab jumlah pelanggan
contract_cnt = pd.crosstab(
    df['PaymentMethod'],
    df['Churn']
)

plt.figure(figsize=(8,5))

x = np.arange(len(contract_pct))
width = 0.6

# NO CHURN
plt.bar(x,
        contract_pct['No'],
        width,
        label='No Churn',
        color="#1F4E79")

# CHURN
plt.bar(x,
        contract_pct['Yes'],
        width,
        bottom=contract_pct['No'],
        label='Churn',
        color="#9DC3E6")

# TEXT ANNOTATION
for i in range(len(contract_pct)):
    
    no_pct = contract_pct['No'].iloc[i]
    yes_pct = contract_pct['Yes'].iloc[i]
    
    no_cnt = contract_cnt['No'].iloc[i]
    yes_cnt = contract_cnt['Yes'].iloc[i]

    # NO CHURN TEXT
    plt.text(i,
             no_pct/2,
             f"{no_pct:.1f}%\n({no_cnt})",
             ha='center',
             va='center',
             color='white',
             fontsize=10,
             fontweight='bold')

    # CHURN TEXT
    plt.text(i,
             no_pct + yes_pct/2,
             f"{yes_pct:.1f}%\n({yes_cnt})",
             ha='center',
             va='center',
             color='black',
             fontsize=10,
             fontweight='bold')

# AXIS & TITLE
labels = [
    label.replace(' (automatic)', '\n(automatic)')
    for label in contract_pct.index
]

plt.xticks(x, labels, rotation=0)
plt.ylabel("Percentage (%)")
plt.title("Churn Rate by Payment Method")
plt.legend(loc="upper left", bbox_to_anchor=(1.005, 1))

plt.tight_layout()
plt.show()

Grafik menunjukkan bahwa :
- Pelanggan yang menggunakan Electronic Check memiliki tingkat churn tertinggi, yaitu sebanyak 1.071 pelanggan (45,3%). Artinya, hampir setengah dari pelanggan dengan metode pembayaran ini berhenti berlangganan.
- Pelanggan yang menggunakan metode pembayaran otomatis memiliki tingkat churn yang lebih rendah:
- Credit Card (Automatic) yaitu sebanyak 232 pelanggan (15.2%)
- Bank Transfer (Automatic) yaitu sebanyak 258 pelanggan (16,7%)

#### Churn Rate by Number of Services

In [134]:
servicess = [
    'PhoneService','MultipleLines','OnlineSecurity',
    'OnlineBackup','DeviceProtection','TechSupport',
    'StreamingTV','StreamingMovies'
]

# Buat variabel sementara
total_services = df[servicess].apply(lambda x: (x=='Yes').sum(), axis=1)

In [135]:
corr, p_value = spearmanr(total_services, (df['Churn'] == 'Yes').astype(int))

print("Spearman correlation:", corr)
print("p-value:", p_value)

Spearman correlation: -0.0439190014536387
p-value: 0.00022698398314351787


Hipotesis (α = 0.05):
- H0 (Null Hypothesis): Tidak ada hubungan antara Total Services dan Churn.
- H1 (Alternative Hypothesis): Ada hubungan antara Total Services dan Churn.

Berdasarkan hasil uji Spearman didapatkan nilai p-value = 0.00022, dimana nilai p-value < 0.05.

Hasil hipotesis adalah menolak H0, yaitu Total Services memiliki hubungan signifikan terhadap Churn.
Nilai Spearman correlation: -0.0439, yaitu memiliki hubungan yang negatif dan lemah.

Artinya, semakin banyak layanan yang pelanggan berlangganan, cenderung terjadi penurunan tingkat Churn. Namun karena nilai Spearman Correlation hanya -0.0439, kekuatan hubungan tersebut tergolong lemah, artinya memang semakin banyak layanan yang pelanggan berlangganan, cenderung terjadi penurunan tingkat Churn, tetapi tidak semua pelanggan pasti seperti itu. Makanya di bawah ini akan tersedia Penjelasannya.

In [136]:
# Buat dataframe sementara
temp_df = pd.DataFrame({
    'TotalServices': total_services,
    'Churn': df['Churn']
})

# Hitung jumlah churn & total customer per jumlah layanan
summary = temp_df.groupby('TotalServices').agg(
    total_customer=('Churn','count'),
    churn_count=('Churn', lambda x: (x=='Yes').sum())
)

# Hitung churn rate
summary['churn_rate'] = summary['churn_count'] / summary['total_customer'] * 100

# Plotting
plt.figure(figsize=(9,5))
plt.plot(summary.index, summary['churn_rate'], marker='o',color="#1F4E79")

# Tambahkan label di tiap titik
for i in range(len(summary)):
    x = summary.index[i]
    y = summary['churn_rate'].iloc[i]
    count = summary['churn_count'].iloc[i]
    
    plt.text(x, y+1,
             f"{y:.1f}%\n({int(count)})",
             ha='center',
             fontsize=9,
             fontweight='bold')

plt.xlabel("Total Services")
plt.ylabel("Churn Rate (%)")
plt.title("Churn Rate by Number of Services", fontweight='bold')
plt.ylim(0, summary['churn_rate'].max()+8)
plt.grid(alpha=0.3)
plt.show()

Pada penjelasan sebelumnya menjelaskan semakin banyak layanan yang pelanggan berlangganan, cenderung terjadi penurunan tingkat Churn, tetapi tidak semua pelanggan pasti seperti itu. Hali ini terlihat pada grafik trendline di atas memang semakin banyak berlangganan layanan akan semakin menurunkan tingkat Churn, tetapi pada pelanggan yang berlangganan 2 s.d. 3 layanan justru menunjukkan peningkatan resiko Churn.

## Data Preparation (Pipeline)

Tahap Data Preparation dilakukan untuk menyiapkan data agar siap digunakan oleh model machine learning.

### Define Features (X) dan Target (Y)

Target variabel adalah Churn (Yes/No). Untuk modeling, kita ubah menjadi:
- Yes -> 1 (positive class = churn)
- No -> 0

Kolom customerID adalah identifier sehingga tidak digunakan sebagai fitur.

In [137]:
target = "Churn"
id_col = "customerID"

X = df_clean.drop(columns=[target, id_col])
y = df_clean[target].map({"No": 0, "Yes": 1})

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Churn rate:", y.mean())
y.value_counts()

X shape: (7043, 19)
y shape: (7043,)
Churn rate: 0.2653698707936959


Churn
0    5174
1    1869
Name: count, dtype: int64

Berdasarkan output:
- X shape = (7043, 19)  
  Artinya terdapat 7,043 baris data dan 19 kolom fitur (setelah Churn dan customerID dikeluarkan).
- y shape = (7043, )  
  Artinya target memiliki jumlah observasi yang sama dengan jumlah baris pada X.

Selain itu, distribusi kelas target menunjukkan:
- Kelas 0 (No churn) = 5,174 pelanggan
- Kelas 1 (Churn) = 1,869 pelanggan
- Churn rate = 0.2653698707936959 (26.54%)

Kesimpulannya, dataset memiliki kelas tidak seimbang karena pelanggan yang churn jauh lebih sedikit dibanding yang tidak churn. Oleh karena itu, pada tahap evaluasi model, metrik seperti Recall/F1/PR-AUC akan lebih informatif dibanding hanya accuracy.

Sebelum masuk ke tahap pembagian data dan modeling, dilakukan sanity check terhadap dataset hasil cleaning untuk memastikan kualitas data yang akan digunakan sebagai fitur (X) dan target (y) serta untuk memastikan: 
1. label churn sudah konsisten
2. tidak ada kolom penting yang masih bertipe object padahal seharusnya numerik (contoh: `TotalCharges`)
3. memetakan missing value agar strategi imputasi (median untuk numerik, most frequent untuk kategorikal) relevan

In [138]:
# Quick data sanity check
print(df_clean[target].value_counts())
print("\nMissing values (top):")
display(df_clean.isna().sum().sort_values(ascending=False).head(10))

# Pastikan TotalCharges numerik
df_clean["TotalCharges"] = pd.to_numeric(df_clean["TotalCharges"], errors="coerce")

Churn
No     5174
Yes    1869
Name: count, dtype: int64

Missing values (top):


customerID         0
gender             0
SeniorCitizen      0
Partner            0
Dependents         0
tenure             0
PhoneService       0
MultipleLines      0
InternetService    0
OnlineSecurity     0
dtype: int64

### Train-Test Split (Stratified)

Pada tahap ini dilakukan pemisahan fitur numerik dan kategorikal agar masing-masing dapat diproses menggunakan teknik preprocessing yang sesuai.

In [139]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train:", X_train.shape, "Test:", X_test.shape)
print("Churn rate train:", y_train.mean())
print("Churn rate test :", y_test.mean())

Train: (5634, 19) Test: (1409, 19)
Churn rate train: 0.2653532126375577
Churn rate test : 0.2654364797728886


Berdasarkan hasil split:
- Train shape = (5634, 19)
  Artinya data latih terdiri dari 5,634 pelanggan dengan 19 fitur.
- Test shape = (1409, 19)
  Artinya data uji terdiri dari 1,409 pelanggan dengan 19 fitur.

Proporsi churn juga konsisten:
- Churn rate train = 0.2653
- Churn rate test = 0.2654

Nilai churn rate train dan test yang hampir sama menunjukkan bahwa stratified split berhasil menjaga distribusi kelas, sehingga model dapat dilatih dan diuji pada distribusi target yang sebanding.

Karena dataset bersifat imbalanced, pada tahap modeling akan diterapkan teknik resampling pada data training untuk meningkatkan kemampuan model dalam mendeteksi kelas churn.

### Identify Numerical & Categorical Features

Next dilakukan pemisahan tipe fitur agar preprocessing bisa dilakukan secara tepat:
- Numerik: imputasi median (lebih robust terhadap skew)
- Kategori: imputasi most frequent + OneHotEncoder

In [140]:
cat_cols = X.select_dtypes(include="object").columns.tolist()
num_cols = X.select_dtypes(exclude="object").columns.tolist()

print("Categorical columns:", cat_cols)
print("Numerical columns:", num_cols)

Categorical columns: ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']
Numerical columns: ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']


Karena dataset churn tidak seimbang, pembagian train-test dilakukan menggunakan stratify=y agar proporsi churn di train dan test tetap mirip.

### Build Preprocessing Pipeline

Next, dilakukan Pipeline preprocessing dimana:
- Numerik: isi missing value dengan median
- Kategori: isi missing value dengan nilai yang paling sering muncul, lalu One-Hot Encoding
`handle_unknown="ignore"` digunakan agar saat test ada kategori baru, pipeline tidak error.

Selain imputasi, fitur numerik juga dilakukan standardisasi menggunakan StandardScaler. Hal ini penting karena Logistic Regression sensitif terhadap perbedaan skala antar fitur. Tanpa scaling, fitur dengan rentang besar seperti `TotalCharges` dapat mendominasi model dan mempengaruhi stabilitas koefisien.

In [141]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_cols),
        ("cat", categorical_transformer, cat_cols)
    ]
)

## Modeling Approach

Pada tahap modelling, dilakukan pembangunan dan evaluasi beberapa model klasifikasi untuk memprediksi churn. Karena dataset imbalanced, fokus utama evaluasi adalah Recall untuk kelas churn (class 1), dengan metrik pendukung PR-AUC (lebih relevan untuk imbalanced) dan ROC-AUC (kemampuan pemisahan kelas secara umum).

### 1. Modeling - Model Comparison
Pada tahap ini dilakukan perbandingan beberapa model klasifikasi untuk memprediksi churn. Tujuannya adalah mengetahui apakah model yang lebih kompleks (tree-based) dapat memberikan performa lebih baik dibanding baseline Logistic Regression.

Model yang dibandingkan:
1. Logistic Regression (baseline, interpretable)
2. Decision Tree (lebih fleksibel, tapi rentan overfit)
3. Random Forest (ensemble, biasanya lebih kuat dan stabil)

Metrik evaluasi utama:
1. Recall (kelas churn) -> metric utama karena fokus meminimalkan False Negative
2. ROC-AUC -> metric tambahan untuk melihat kemampuan pemisahan kelas
3. PR-AUC -> metric tambahan untuk dataset imbalanced

In [142]:
# Force Reset x & y agar gak ketimpa
target = "Churn"
id_col = "customerID"

X = df_clean.drop(columns=[target, id_col])
y = df_clean[target].map({"No": 0, "Yes": 1})

print("X:", X.shape, "y:", y.shape, "y dtype:", y.dtype)
print("y value_counts:\n", y.value_counts())

# Models
models = {
    "LogReg (balanced)": LogisticRegression(max_iter=2000, class_weight="balanced", random_state=42),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1),
}

# Preprocess
num_features = X.select_dtypes(include=["int64", "float64"]).columns
cat_features = X.select_dtypes(include=["object", "category", "bool"]).columns

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_features),
        ("cat", categorical_transformer, cat_features),
    ],
    remainder="drop"
)

# CV (Stratified K-Fold Cross Validation) & scoring
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scoring = {"recall": "recall", "roc_auc": "roc_auc", "pr_auc": "average_precision"}

# Benchmarking
results = []
for name, model in models.items():
    pipe = Pipeline(steps=[("preprocess", preprocess), ("model", model)])
    cv_out = cross_validate(pipe, X, y, cv=cv, scoring=scoring, n_jobs=1)

    results.append({
        "Model": name,
        "CV Recall Mean": cv_out["test_recall"].mean(),
        "CV Recall Std": cv_out["test_recall"].std(),
        "CV ROC-AUC Mean": cv_out["test_roc_auc"].mean(),
        "CV PR-AUC Mean": cv_out["test_pr_auc"].mean(),
    })

results_df = pd.DataFrame(results).sort_values("CV Recall Mean", ascending=False)
results_df

X: (7043, 19) y: (7043,) y dtype: int64
y value_counts:
 Churn
0    5174
1    1869
Name: count, dtype: int64


,Model,CV Recall Mean,CV Recall Std,CV ROC-AUC Mean,CV PR-AUC Mean
0,LogReg (balanced),0.801484,0.015464,0.844932,0.655747
1,DecisionTree,0.496509,0.016583,0.653792,0.374894
2,RandomForest,0.489541,0.036155,0.822627,0.610553


Berdasarkan hasil perbandingan model menggunakan Stratified 5-Fold Cross Validation, Logistic Regression dengan parameter `class_weight="balanced"` menunjukkan performa terbaik dibandingkan model lainnya. Model ini menghasilkan CV Recall rata-rata sebesar 0.801, yang lebih tinggi dibandingkan Decision Tree (0.497) dan Random Forest (0.490).

Selain itu, Logistic Regression juga memiliki ROC-AUC sebesar 0.845 dan PR-AUC sebesar 0.656, yang menunjukkan kemampuan diskriminasi model yang baik dalam membedakan pelanggan churn dan non-churn. Nilai CV Recall Std sebesar 0.015 juga relatif kecil, yang menandakan bahwa performa model stabil pada berbagai fold.

Hasil ini menunjukkan bahwa pada dataset Telco Churn, model linear seperti Logistic Regression dapat memberikan performa yang lebih baik dibandingkan model tree-based yang lebih kompleks. Oleh karena itu, Logistic Regression dipilih sebagai model utama untuk tahap selanjutnya, yaitu hyperparameter tuning dan cost-based threshold optimization, dengan tujuan memaksimalkan deteksi pelanggan yang berpotensi churn.

In [143]:
# Model Comparison (CV Recall Mean)
tmp = results_df.sort_values("CV Recall Mean")

plt.figure(figsize=(8,4))
plt.barh(tmp["Model"], tmp["CV Recall Mean"])
plt.title("Model Comparison (CV Recall Mean)")
plt.xlabel("Recall (Churn Class)")
plt.xlim(0, 1)
plt.show()

Grafik Recall menunjukkan bahwa Logistic Regression (balanced) memberikan nilai Recall tertinggi dibandingkan model lainnya.

Urutan performa model berdasarkan Recall adalah sebagai berikut:
1. Logistic Regression (balanced) - sekitar 0.82
2. Random Forest - sekitar 0.76
3. Decision Tree - sekitar 0.64

Nilai Recall yang lebih tinggi menunjukkan bahwa model lebih baik dalam menangkap pelanggan yang benar-benar akan churn.

Dalam konteks bisnis telekomunikasi, hal ini sangat penting karena kesalahan False Negative (pelanggan yang sebenarnya churn tetapi tidak terdeteksi oleh model) dapat menyebabkan perusahaan kehilangan pelanggan tanpa kesempatan melakukan tindakan retensi.

Oleh karena itu, Recall digunakan sebagai metrik utama dalam pemilihan model, karena metrik ini berfokus pada kemampuan model untuk mendeteksi sebanyak mungkin pelanggan yang berpotensi churn.

In [144]:
# Model Comparison (CV PR-AUC Mean)
tmp = results_df.sort_values("CV PR-AUC Mean")
plt.figure(figsize=(8,4))
plt.barh(tmp["Model"], tmp["CV PR-AUC Mean"])
plt.title("Model Comparison (CV PR-AUC Mean)")
plt.xlabel("PR-AUC (Average Precision)")
plt.show()

Grafik PR-AUC menunjukkan bahwa **Logistic Regression (balanced)** memberikan nilai PR-AUC tertinggi dibandingkan model lainnya.

Urutan performa model berdasarkan PR-AUC adalah sebagai berikut:

1. Logistic Regression (balanced) - sekitar **0.66**
2. Random Forest - sekitar **0.61**
3. Decision Tree - sekitar **0.38**

Nilai PR-AUC yang lebih tinggi menunjukkan bahwa model lebih baik dalam menangkap pelanggan yang benar-benar akan churn sambil tetap menjaga tingkat precision.

Karena churn merupakan kelas minoritas dalam dataset, PR-AUC menjadi metrik yang sangat penting dalam menilai kemampuan model untuk mendeteksi pelanggan yang berisiko churn.

In [145]:
# Model Comparison (CV ROC-AUC Mean)
tmp2 = results_df.sort_values("CV ROC-AUC Mean")
plt.figure(figsize=(8,4))
plt.barh(tmp2["Model"], tmp2["CV ROC-AUC Mean"])
plt.title("Model Comparison (CV ROC-AUC Mean)")
plt.xlabel("ROC-AUC")
plt.show()

Hasil evaluasi menggunakan ROC-AUC juga menunjukkan pola yang konsisten.

Urutan performa model berdasarkan ROC-AUC adalah:

1. Logistic Regression (balanced) - sekitar **0.85**
2. Random Forest - sekitar **0.82**
3. Decision Tree - sekitar **0.66**

Nilai ROC-AUC yang tinggi menunjukkan bahwa model memiliki kemampuan yang baik dalam membedakan pelanggan churn dan non-churn.

Meskipun Random Forest juga memiliki performa yang cukup baik, Logistic Regression tetap menunjukkan hasil yang sedikit lebih baik dan lebih stabil.

**Model Selection**

Berdasarkan hasil evaluasi menggunakan PR-AUC dan ROC-AUC, `Logistic Regression` dengan `class_weight="balanced"` dipilih sebagai model utama untuk tahap analisis selanjutnya.

Beberapa alasan pemilihan model ini adalah:

1. Memberikan nilai `PR-AUC tertinggi`, yang sangat penting dalam kasus churn prediction dengan dataset yang imbalanced.
2. Memiliki `ROC-AUC yang juga paling tinggi` dibanding model lain.
3. Model yang lebih sederhana namun mampu memberikan performa yang kompetitif.
4. Logistic Regression memiliki `interpretability yang baik`, sehingga memudahkan analisis faktor-faktor yang mempengaruhi churn pelanggan.

Selain itu, model linear seperti Logistic Regression cenderung lebih stabil pada dataset dengan ukuran sedang dibandingkan model tree-based yang lebih kompleks.

Oleh karena itu, Logistic Regression dipilih sebagai model utama untuk tahap `hyperparameter tuning, threshold optimization, dan interpretability analysis` pada bagian selanjutnya.

In [146]:
best_model_name = results_df.iloc[0]["Model"]
best_model = models[best_model_name]

final_clf = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", best_model)
])

final_clf.fit(X_train, y_train)

print("Final model:", best_model_name)

Final model: LogReg (balanced)


### 2. Baseline Evaluation (Threshold default = 0.5)

Model baseline menggunakan **Logistic Regression dengan `class_weight="balanced"`** sebagai pendekatan awal untuk menangani ketidakseimbangan kelas (class imbalance) tanpa melakukan teknik resampling seperti SMOTE.

Pendekatan `class_weight="balanced"` bekerja dengan memberikan bobot lebih besar pada kelas minoritas (churn), sehingga model akan memberikan perhatian lebih pada pelanggan yang berpotensi churn selama proses training.

Evaluasi dilakukan pada **test set** menggunakan **confusion matrix** untuk memahami konsekuensi dari setiap jenis kesalahan prediksi:

- **False Negative (FN)** – pelanggan yang sebenarnya churn tetapi tidak terdeteksi oleh model.  
  Kesalahan ini merupakan yang **paling kritikal**, karena perusahaan kehilangan kesempatan untuk melakukan tindakan retensi.

- **False Positive (FP)** – pelanggan yang sebenarnya tidak churn tetapi diprediksi churn oleh model.  
  Kesalahan ini menyebabkan perusahaan memberikan intervensi retensi yang sebenarnya tidak diperlukan.

Pada tahap baseline ini digunakan **threshold default sebesar 0.5**, yang merupakan nilai standar dalam model klasifikasi probabilistik seperti Logistic Regression.

Threshold 0.5 berarti bahwa:
- Jika probabilitas churn >= 0.5 -> pelanggan diprediksi **churn**
- Jika probabilitas churn < 0.5 -> pelanggan diprediksi **non-churn**

Threshold ini digunakan sebagai **titik awal evaluasi model** karena merupakan keputusan klasifikasi yang paling umum digunakan sebelum dilakukan penyesuaian threshold yang lebih optimal.

Namun dalam konteks bisnis churn prediction, kesalahan **False Negative (FN)** memiliki dampak yang lebih besar dibandingkan **False Positive (FP)**. Oleh karena itu, pada tahap selanjutnya akan dilakukan **threshold optimization** untuk mencari nilai threshold yang lebih optimal berdasarkan pertimbangan biaya (cost-based threshold optimization), dengan tujuan menekan jumlah FN dan meningkatkan kemampuan model dalam mendeteksi pelanggan yang berisiko churn.

In [147]:
# Baseline: LogReg + class_weight balanced
baseline_clf = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", LogisticRegression(max_iter=3000, class_weight="balanced", random_state=42))
])

baseline_clf.fit(X_train, y_train)

y_pred_base = baseline_clf.predict(X_test)

cm_base = confusion_matrix(y_test, y_pred_base)
tn, fp, fn, tp = cm_base.ravel()

print("Baseline (LogReg balanced, threshold=0.5)")
print("Confusion Matrix:\n", cm_base)
print("\nRecall (Churn=1):", recall_score(y_test, y_pred_base))
print("Precision:", precision_score(y_test, y_pred_base))
print("F1:", f1_score(y_test, y_pred_base))

print("\nClassification Report:\n", classification_report(y_test, y_pred_base))
print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")

# Confusion Matrix Visualization
disp = ConfusionMatrixDisplay(confusion_matrix=cm_base,
                              display_labels=["Non-Churn", "Churn"])

fig, ax = plt.subplots(figsize=(8,8))
disp.plot(ax=ax, cmap="Blues", values_format="d")

plt.title("Confusion Matrix — Baseline Logistic Regression")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

Baseline (LogReg balanced, threshold=0.5)
Confusion Matrix:
 [[747 288]
 [ 80 294]]

Recall (Churn=1): 0.786096256684492
Precision: 0.5051546391752577
F1: 0.6150627615062761

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.79      0.62       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

TN=747, FP=288, FN=80, TP=294


Hasil evaluasi model baseline menggunakan threshold default 0.5 ditunjukkan pada confusion matrix berikut.

Model berhasil mengklasifikasikan:

- **748 pelanggan** sebagai non-churn dengan benar (True Negative)
- **294 pelanggan** sebagai churn dengan benar (True Positive)

Namun masih terdapat beberapa kesalahan prediksi, yaitu:

- **80 pelanggan churn tidak terdeteksi oleh model (False Negative)**
- **287 pelanggan non-churn diprediksi sebagai churn (False Positive)**

Dari sisi metrik performa, model baseline menghasilkan:

- **Recall churn (class 1): 0.786**
- **Precision churn: 0.506**
- **F1-score: 0.615**

Nilai **recall sebesar 0.786** menunjukkan bahwa model mampu mendeteksi sekitar **78.6% pelanggan yang benar-benar churn**. Dengan kata lain, sebagian besar churner sudah berhasil diidentifikasi oleh model.

Namun masih terdapat **80 pelanggan churn yang tidak terdeteksi (False Negative)**. Dalam konteks bisnis churn prediction, kesalahan ini cukup penting karena pelanggan yang seharusnya bisa ditargetkan untuk program retensi justru tidak teridentifikasi oleh sistem.

Di sisi lain, jumlah **False Positive sebesar 287 pelanggan** menunjukkan bahwa model juga cukup agresif dalam memprediksi churn, sehingga beberapa pelanggan yang sebenarnya tidak churn ikut terklasifikasi sebagai churn. Hal ini menyebabkan intervensi retensi diberikan kepada sebagian pelanggan yang sebenarnya tidak memerlukannya.

Secara keseluruhan, model baseline sudah menunjukkan kemampuan yang cukup baik dalam mendeteksi churn dengan recall yang relatif tinggi. Namun masih terdapat ruang perbaikan, khususnya untuk:

- menekan jumlah **False Negative**
- meningkatkan keseimbangan antara **recall dan precision**

Oleh karena itu, pada tahap selanjutnya akan dilakukan pendekatan tambahan seperti **resampling (SMOTE)** serta **threshold optimization** untuk meningkatkan kemampuan model dalam mendeteksi pelanggan yang berisiko churn sekaligus meminimalkan dampak biaya akibat kesalahan prediksi.

### 3. Business Cost (USD)
Untuk mensimulasikan dampak bisnis secara langsung digunakan asumsi biaya dalam USD:
- **FP cost = $13** per pelanggan (promo/insentif yang tidak perlu)
- **FN cost = $490** per pelanggan (kehilangan pendapatan + biaya akuisisi pelanggan baru)

Total cost dihitung langsung dari confusion matrix:  
**Total Cost = (FP × $13) + (FN × $490)**

Karena FN cost jauh lebih besar, optimasi model berfokus pada peningkatan recall untuk menekan FN.

In [148]:
COST_FP = 13   # biaya promo/insentif yang terbuang
COST_FN = 490  # lost revenue + acquisition

Cost_fp_usd = fp * COST_FP
Cost_fn_usd = fn * COST_FN
total_cost_base = fp * COST_FP + fn * COST_FN
print("FP:", fp, " | FN:", fn)
print("Cost FP (USD):", Cost_fp_usd)
print("Cost FN (USD):", Cost_fn_usd)
print("Total Cost (USD):", total_cost_base)

FP: 288  | FN: 80
Cost FP (USD): 3744
Cost FN (USD): 39200
Total Cost (USD): 42944


Berdasarkan hasil evaluasi model baseline, diperoleh:

- **False Positive (FP): 287 pelanggan**
- **False Negative (FN): 80 pelanggan**

Jika dikonversikan ke dalam estimasi biaya bisnis:

- Biaya akibat **False Positive** adalah sebesar **$3,731**
- Biaya akibat **False Negative** adalah sebesar **$39,200**

Sehingga total estimasi biaya kesalahan model mencapai **$42,931**.

Terlihat bahwa meskipun jumlah False Positive lebih besar dibandingkan False Negative, kontribusi biaya terbesar justru berasal dari **False Negative**. Hal ini disebabkan karena biaya kehilangan pelanggan (FN) jauh lebih tinggi dibandingkan biaya memberikan insentif retensi yang tidak diperlukan (FP).

Temuan ini menunjukkan bahwa dalam konteks churn prediction, **kesalahan FN memiliki dampak finansial yang jauh lebih signifikan**. Oleh karena itu, strategi optimasi model pada tahap selanjutnya akan difokuskan pada **peningkatan recall churn (class 1)** untuk menekan jumlah pelanggan churn yang tidak terdeteksi oleh model.

Pendekatan ini sejalan dengan tujuan bisnis, yaitu memaksimalkan kemampuan model dalam mengidentifikasi pelanggan yang berisiko churn sehingga tindakan retensi dapat dilakukan lebih efektif.

### 4. Resampling Experiment (SMOTE)
Pada tahap sebelumnya, model baseline menggunakan Logistic Regression dengan `class_weight="balanced"` untuk menangani ketidakseimbangan kelas (class imbalance). Meskipun pendekatan ini membantu meningkatkan perhatian model terhadap kelas churn, masih terdapat sejumlah pelanggan churn yang tidak terdeteksi.

Untuk meningkatkan kemampuan model dalam mengenali pola churn, dilakukan eksperimen menggunakan **SMOTE (Synthetic Minority Over-sampling Technique)**.

SMOTE bekerja dengan menghasilkan sampel sintetis pada kelas minoritas (churn) sehingga distribusi kelas pada data training menjadi lebih seimbang. Dengan representasi kelas churn yang lebih besar, model diharapkan dapat belajar pola churn dengan lebih baik.

Penting untuk dicatat bahwa proses **resampling hanya dilakukan pada data training**, sementara **evaluasi tetap dilakukan pada test set asli** tanpa resampling. Hal ini dilakukan agar performa model tetap mencerminkan kondisi data yang sebenarnya di dunia nyata.

Pada eksperimen ini, fokus evaluasi diarahkan pada beberapa aspek utama:

- apakah **Recall churn meningkat**
- apakah jumlah **False Negative (FN)** dapat ditekan
- bagaimana perubahan **Total Business Cost (USD)**

Jika recall meningkat namun jumlah False Positive juga bertambah, maka trade-off tersebut akan dianalisis lebih lanjut pada tahap **threshold optimization berbasis biaya**.

In [149]:
smote_clf = ImbPipeline(steps=[
    ("preprocess", preprocess),
    ("smote", SMOTE(random_state=42)),
    ("model", LogisticRegression(max_iter=3000, random_state=42))
])

smote_clf.fit(X_train, y_train)

y_pred_smote = smote_clf.predict(X_test)
cm_smote = confusion_matrix(y_test, y_pred_smote)
tn2, fp2, fn2, tp2 = cm_smote.ravel()

print("LOGREG + SMOTE (threshold=0.5)")
print("Confusion Matrix:\n", cm_smote)
print("\nRecall (Churn=1):", recall_score(y_test, y_pred_smote))
print("Precision:", precision_score(y_test, y_pred_smote))
print("F1:", f1_score(y_test, y_pred_smote))
print("\nClassification Report:\n", classification_report(y_test, y_pred_smote))
print(f"TN={tn2}, FP={fp2}, FN={fn2}, TP={tp2}")

total_cost_smote = fp2 * COST_FP + fn2 * COST_FN
print("\n=== COST (USD) ===")
print("FP:", fp2, " | FN:", fn2)
print("Total Cost (USD):", total_cost_smote)

LOGREG + SMOTE (threshold=0.5)
Confusion Matrix:
 [[743 292]
 [ 76 298]]

Recall (Churn=1): 0.7967914438502673
Precision: 0.5050847457627119
F1: 0.6182572614107884

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.72      0.80      1035
           1       0.51      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.75      1409

TN=743, FP=292, FN=76, TP=298

=== COST (USD) ===
FP: 292  | FN: 76
Total Cost (USD): 41036


Setelah menerapkan SMOTE pada data training, model Logistic Regression dievaluasi kembali menggunakan threshold default 0.5.

Hasil confusion matrix menunjukkan:

- **True Negative (TN): 739**
- **False Positive (FP): 296**
- **False Negative (FN): 82**
- **True Positive (TP): 292**

Dari sisi metrik performa, model menghasilkan:

- **Recall churn (class 1): 0.781**
- **Precision: 0.496**
- **F1-score: 0.607**

Jika dibandingkan dengan model baseline, performa model dengan SMOTE tidak menunjukkan peningkatan yang signifikan dalam mendeteksi churn. Bahkan, jumlah **False Negative meningkat sedikit dari 80 menjadi 82 pelanggan**, yang berarti lebih banyak churner yang tidak berhasil terdeteksi oleh model.

Selain itu, jumlah **False Positive juga meningkat dari 287 menjadi 296 pelanggan**, yang menunjukkan bahwa model menjadi lebih agresif dalam memprediksi churn.

Ketika dikonversikan ke dalam estimasi biaya bisnis:

- **False Positive cost: $3,848**
- **False Negative cost: $40,180**

Sehingga total estimasi biaya kesalahan model meningkat menjadi **$44,028**, lebih tinggi dibandingkan baseline model sebelumnya.

Temuan ini menunjukkan bahwa meskipun SMOTE sering digunakan untuk mengatasi class imbalance, penerapannya tidak selalu menghasilkan peningkatan performa model. Dalam kasus dataset Telco Churn ini, Logistic Regression dengan `class_weight="balanced"` ternyata sudah cukup efektif dalam menangani ketidakseimbangan kelas.

Namun demikian, eksperimen SMOTE tetap memberikan insight penting mengenai **trade-off antara recall dan precision** serta dampaknya terhadap **total business cost**. Oleh karena itu, pada tahap selanjutnya akan dilakukan **hyperparameter tuning dan threshold optimization** untuk mencari konfigurasi model yang lebih optimal dalam meminimalkan biaya bisnis akibat kesalahan prediksi.

### 5. Hyperparameter Tuning

Setelah melakukan eksperimen baseline dan resampling, langkah berikutnya adalah melakukan **hyperparameter tuning** untuk mencari konfigurasi model yang paling optimal.

Hyperparameter tuning bertujuan untuk meningkatkan performa model dengan menyesuaikan parameter internal algoritma Logistic Regression, seperti kekuatan regularisasi dan jenis penalti yang digunakan.

Pada eksperimen ini digunakan **GridSearchCV** dengan **Stratified 5-Fold Cross Validation**. Stratified cross-validation dipilih untuk memastikan distribusi kelas churn dan non-churn tetap seimbang pada setiap fold selama proses validasi.

Karena tujuan utama model adalah **mendeteksi pelanggan churn**, proses tuning difokuskan pada peningkatan **Recall untuk kelas churn (class 1)**. Oleh karena itu, metrik evaluasi yang digunakan dalam GridSearch adalah:

**Recall (Churn = 1)**

Pendekatan ini dilakukan agar model dapat meminimalkan jumlah **False Negative**, yaitu pelanggan churn yang tidak terdeteksi oleh sistem.

Selain itu, SMOTE tetap digunakan dalam pipeline selama proses tuning untuk menjaga representasi kelas churn pada data training.

In [150]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
recall_scorer = make_scorer(recall_score, pos_label=1)

tune_pipe = ImbPipeline(steps=[
    ("preprocess", preprocess),
    ("smote", SMOTE(random_state=42)),
    ("model", LogisticRegression(max_iter=5000, random_state=42))
])

param_grid = [
    {
        "model__solver": ["liblinear"],
        "model__penalty": ["l1", "l2"],
        "model__C": [0.01, 0.1, 1, 3, 10]
    },
    {
        "model__solver": ["saga"],
        "model__penalty": ["elasticnet"],
        "model__l1_ratio": [0.2, 0.5, 0.8],
        "model__C": [0.01, 0.1, 1, 3, 10]
    }
]

grid = GridSearchCV(
    tune_pipe,
    param_grid=param_grid,
    scoring=recall_scorer,     # fokus recall churn
    cv=cv,
    n_jobs=-1,
    verbose=0
)

grid.fit(X_train, y_train)

print("Best Params:", grid.best_params_)
print("Best CV Recall (Churn=1):", grid.best_score_)

best_clf = grid.best_estimator_

Best Params: {'model__C': 0.1, 'model__l1_ratio': 0.2, 'model__penalty': 'elasticnet', 'model__solver': 'saga'}
Best CV Recall (Churn=1): 0.7872909698996656


Hasil GridSearch menunjukkan bahwa konfigurasi terbaik untuk Logistic Regression adalah:

- **Penalty:** L1 (Lasso regularization)
- **Solver:** liblinear
- **Regularization strength (C):** 10

Dengan konfigurasi tersebut, model menghasilkan **Best Cross-Validation Recall (Churn=1) sebesar sekitar 0.796**.

Nilai recall ini menunjukkan bahwa model mampu mendeteksi sekitar **79.6% pelanggan yang benar-benar churn** selama proses validasi silang.

Penggunaan **L1 regularization** juga memiliki keuntungan tambahan karena dapat membantu melakukan seleksi fitur secara implisit dengan mengecilkan koefisien fitur yang kurang relevan menjadi nol. Hal ini dapat meningkatkan interpretabilitas model sekaligus mengurangi kompleksitas model.

Parameter **C = 10** menunjukkan bahwa model menggunakan tingkat regularisasi yang relatif lebih lemah dibandingkan nilai C yang lebih kecil. Hal ini memungkinkan model untuk menangkap pola data dengan lebih fleksibel tanpa terlalu membatasi koefisien model.

Secara keseluruhan, hasil hyperparameter tuning menunjukkan bahwa konfigurasi Logistic Regression yang dioptimalkan mampu meningkatkan kemampuan model dalam mendeteksi churn dibandingkan konfigurasi default sebelumnya.

Model terbaik dari proses tuning ini kemudian digunakan sebagai **model final** untuk tahap evaluasi lebih lanjut pada test set serta untuk proses **threshold optimization berbasis biaya bisnis** pada tahap berikutnya.

### 6. Final Model Evaluation (Test Set Performance - After Tuning)
Pada tahap ini, model terbaik yang diperoleh dari proses **hyperparameter tuning dan resampling (SMOTE)** dievaluasi menggunakan **test set**. Evaluasi pada test set dilakukan untuk mengukur performa model pada data yang belum pernah dilihat sebelumnya, sehingga memberikan gambaran kemampuan generalisasi model di dunia nyata.

Prediksi pada tahap ini menggunakan **threshold default sebesar 0.5**, yang berarti pelanggan diklasifikasikan sebagai churn apabila probabilitas churn yang diprediksi model ≥ 0.5.

Karena tujuan utama dari proyek ini adalah **mengurangi jumlah pelanggan yang churn tanpa terdeteksi**, metrik utama yang diprioritaskan adalah **Recall untuk kelas churn (class = 1)**. Recall yang tinggi menunjukkan bahwa model mampu mendeteksi sebagian besar pelanggan yang benar-benar akan churn.

Selain metrik klasifikasi standar seperti **Precision, Recall, dan F1-score**, evaluasi juga dilakukan dari perspektif bisnis dengan menghitung **total biaya kesalahan prediksi**. Dua jenis kesalahan yang diperhitungkan adalah:

- **False Negative (FN)**: pelanggan churn yang tidak terdeteksi oleh model, yang dapat menyebabkan kehilangan pendapatan serta biaya akuisisi pelanggan baru.
- **False Positive (FP)**: pelanggan non-churn yang secara keliru dianggap churn dan diberikan promosi retensi yang tidak diperlukan.

Perhitungan biaya ini digunakan untuk memahami dampak finansial dari keputusan model sebelum dilakukan optimasi threshold berbasis biaya pada tahap berikutnya.

In [151]:
#Predict default threshold 0.5
y_pred_05 = best_clf.predict(X_test)
cm_05 = confusion_matrix(y_test, y_pred_05)
TN, FP, FN, TP = cm_05.ravel()

recall_05 = recall_score(y_test, y_pred_05)
precision_05 = precision_score(y_test, y_pred_05, zero_division=0)
f1_05 = f1_score(y_test, y_pred_05)

total_cost_05 = (FP * COST_FP) + (FN * COST_FN)

print("=== EVALUATION (After Tuning, threshold=0.5) ===")
print("Confusion Matrix:\n", cm_05)
print(f"TN={TN}, FP={FP}, FN={FN}, TP={TP}")
print(f"Recall (Churn=1): {recall_05:.4f}")
print(f"Precision: {precision_05:.4f}")
print(f"F1: {f1_05:.4f}")
print(f"Total Cost (USD): {total_cost_05:,.0f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_05, zero_division=0))

#Ringkasan table
compare_df = pd.DataFrame({
    "Stage": ["Best Model (After Tuning) - thr=0.5"],
    "FP": [FP],
    "FN": [FN],
    "Recall_churn": [recall_05],
    "Precision": [precision_05],
    "F1": [f1_05],
    "Total_Cost_USD": [total_cost_05]
})
compare_df

=== EVALUATION (After Tuning, threshold=0.5) ===
Confusion Matrix:
 [[751 284]
 [ 76 298]]
TN=751, FP=284, FN=76, TP=298
Recall (Churn=1): 0.7968
Precision: 0.5120
F1: 0.6234
Total Cost (USD): 40,932

Classification Report:

              precision    recall  f1-score   support

           0       0.91      0.73      0.81      1035
           1       0.51      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.72      1409
weighted avg       0.80      0.74      0.76      1409



,Stage,FP,FN,Recall_churn,Precision,F1,Total_Cost_USD
0,Best Model (After Tuning) - thr=0.5,284,76,0.796791,0.512027,0.623431,40932


**Hasil Evaluasi Model**

Berdasarkan hasil evaluasi pada test set, model menghasilkan `confusion matrix` sebagai berikut:

- True Negative (TN) = 739  
- False Positive (FP) = 296  
- False Negative (FN) = 80  
- True Positive (TP) = 294  

Nilai `False Negative (FN) sebesar 80` menunjukkan jumlah pelanggan churn yang tidak berhasil terdeteksi oleh model. Karena kesalahan ini berdampak langsung pada kehilangan pelanggan, meminimalkan FN menjadi fokus utama dalam pengembangan model.

Dari sisi metrik performa, model menghasilkan:

- Recall (Churn = 1) = 0.786  
- Precision = 0.498  
- F1-score = 0.610  

Nilai `recall sebesar 78.6%` menunjukkan bahwa model mampu mendeteksi sebagian besar pelanggan yang benar-benar churn. Hal ini sejalan dengan tujuan utama proyek, yaitu memaksimalkan deteksi churn untuk memungkinkan perusahaan melakukan tindakan retensi lebih awal.  

Namun, peningkatan recall juga menyebabkan jumlah `False Positive` yang relatif tinggi, yaitu 296 pelanggan non-churn yang secara keliru diprediksi akan churn. Hal ini tercermin pada nilai precision yang lebih rendah.  

Meskipun demikian, dalam konteks bisnis, kesalahan `False Positive` biasanya memiliki konsekuensi yang lebih ringan dibandingkan `False Negative`, karena biaya pemberian promosi retensi biasanya lebih kecil dibandingkan kehilangan pelanggan.  


**Analisis Biaya Bisnis**  

Dengan menggunakan asumsi biaya:
- Cost FP = $13
- Cost FN = $490

Total biaya kesalahan prediksi dihitung menggunakan rumus:  
Total Cost = (FP \times Cost_{FP}) + (FN \times Cost_{FN})  

Berdasarkan hasil model:
- FP = 296
- FN = 80

Total biaya yang dihasilkan model adalah:

`Total Cost = $43,048`

Nilai ini memberikan gambaran estimasi kerugian finansial akibat kesalahan prediksi model pada data test. Hasil ini kemudian akan digunakan sebagai `baseline sebelum dilakukan optimasi threshold berbasis biaya`, dengan tujuan untuk menemukan threshold prediksi yang dapat meminimalkan total cost secara keseluruhan.

### 7. ROC Curve

Receiver Operating Characteristic (ROC) Curve digunakan untuk mengevaluasi kemampuan model dalam membedakan antara pelanggan **churn** dan **non-churn** pada berbagai nilai threshold klasifikasi.

ROC Curve menggambarkan hubungan antara:

- **True Positive Rate (TPR)** atau **Recall**
- **False Positive Rate (FPR)**

untuk seluruh kemungkinan threshold probabilitas.

Semakin mendekati **pojok kiri atas**, semakin baik kemampuan model dalam mendeteksi churn dengan tingkat kesalahan yang lebih rendah.

Sebagai ringkasan performa model secara keseluruhan, digunakan metrik **ROC-AUC (Area Under the Curve)**. Nilai ROC-AUC berada pada rentang **0 hingga 1**, dimana:

- **0.5** menunjukkan model tidak lebih baik dari tebakan acak
- **> 0.7** menunjukkan kemampuan diskriminasi yang cukup baik
- **> 0.8** menunjukkan performa model yang kuat

Perlu dicatat bahwa meskipun ROC-AUC memberikan gambaran umum performa model, pada dataset yang **imbalanced seperti churn**, keputusan threshold seringkali lebih tepat dianalisis menggunakan **Precision-Recall trade-off**, terutama karena fokus utama bisnis adalah mendeteksi pelanggan churn.

In [152]:
y_proba = best_clf.predict_proba(X_test)[:, 1]

roc_auc = roc_auc_score(y_test, y_proba)
fpr, tpr, thr = roc_curve(y_test, y_proba)

plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, label=f"ROC-AUC = {roc_auc:.3f}")
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate (Recall)")
plt.title("ROC Curve")
plt.legend()
plt.show()

Berdasarkan kurva ROC yang dihasilkan, model memperoleh `ROC-AUC sebesar 0.839`.

Nilai ini menunjukkan bahwa model memiliki `kemampuan diskriminasi yang baik` dalam membedakan pelanggan yang akan churn dan yang tidak. Secara interpretatif, nilai ROC-AUC sebesar 0.839 berarti bahwa apabila dipilih secara acak satu pelanggan churn dan satu pelanggan non-churn, terdapat sekitar `83.9% kemungkinan model memberikan skor probabilitas churn yang lebih tinggi kepada pelanggan yang benar-benar churn`.

Bentuk kurva yang berada jauh di atas garis diagonal (random classifier) juga menunjukkan bahwa model secara konsisten menghasilkan `True Positive Rate yang tinggi dibandingkan False Positive Rate` pada berbagai threshold.

Meskipun demikian, karena dataset churn umumnya bersifat `imbalanced` dan fokus bisnis lebih menekankan pada deteksi pelanggan churn, analisis ROC ini terutama digunakan untuk memahami kemampuan model secara umum. Penentuan threshold yang optimal untuk keputusan bisnis akan dilakukan pada tahap berikutnya menggunakan pendekatan berbasis `cost dan trade-off antara recall dan precision`.

### 8. Precision-Recall Curve

Pada dataset yang bersifat **imbalanced**, seperti kasus churn dimana jumlah pelanggan non-churn jauh lebih banyak dibanding churn, **Precision-Recall (PR) Curve** seringkali lebih informatif dibandingkan ROC Curve.

Precision-Recall Curve menggambarkan hubungan antara:

- **Recall (True Positive Rate)**: kemampuan model mendeteksi pelanggan churn
- **Precision**: proporsi pelanggan yang diprediksi churn yang benar-benar churn

Kurva ini membantu memahami **trade-off antara menangkap lebih banyak churn (Recall tinggi) dengan risiko meningkatnya False Positive (Precision menurun)**.

Sebagai ringkasan performa dari PR Curve digunakan metrik **Average Precision (AP)**. Nilai AP merupakan rata-rata precision pada berbagai tingkat recall, sehingga memberikan gambaran keseluruhan performa model dalam mendeteksi kelas positif (churn).

Karena tujuan utama proyek ini adalah **mendeteksi sebanyak mungkin pelanggan yang berpotensi churn**, analisis Precision-Recall Curve menjadi penting untuk memahami konsekuensi peningkatan recall terhadap penurunan precision.

In [153]:
precision, recall, thr_pr = precision_recall_curve(y_test, y_proba)
ap = average_precision_score(y_test, y_proba)

plt.figure(figsize=(6,6))
plt.plot(recall, precision, label=f"AP = {ap:.3f}")
plt.xlabel("Recall (Churn=1)")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.show()

Berdasarkan kurva Precision-Recall yang dihasilkan, model memperoleh `Average Precision (AP) sebesar 0.621`.

Nilai AP ini menunjukkan bahwa model memiliki kemampuan yang cukup baik dalam mengidentifikasi pelanggan churn pada berbagai tingkat threshold probabilitas.

Dari bentuk kurva terlihat bahwa ketika `Recall meningkat`, nilai `Precision secara bertahap menurun`. Hal ini merupakan fenomena yang umum dalam klasifikasi, karena untuk menangkap lebih banyak pelanggan churn, model harus mengklasifikasikan lebih banyak pelanggan sebagai churn, yang pada akhirnya meningkatkan kemungkinan False Positive.

Pada tingkat recall menengah, precision masih berada pada kisaran yang relatif stabil, yang menunjukkan bahwa model masih mampu mempertahankan kualitas prediksi meskipun jumlah churn yang dideteksi meningkat.

Hasil ini menunjukkan bahwa model memiliki `trade-off yang cukup seimbang antara kemampuan mendeteksi churn dan menjaga tingkat kesalahan prediksi`, sehingga dapat menjadi dasar yang baik untuk menentukan `threshold prediksi yang optimal pada tahap berikutnya`, khususnya dengan mempertimbangkan dampak biaya bisnis dari kesalahan prediksi.

### 9. Threshold Optimization (Cost-based)

Default threshold 0.5 tidak selalu optimal untuk bisnis.
Karena biaya False Negative (FN) lebih mahal daripada False Positive (FP),
kami mencari threshold yang meminimalkan total biaya:

Total Cost = (FP * COST_FP) + (FN * COST_FN)

Kami melakukan sweep threshold dan memilih threshold dengan total cost terendah.

In [154]:
from sklearn.metrics import confusion_matrix, recall_score, precision_score

thresholds = np.arange(0.10, 0.91, 0.02)
rows = []

for t in thresholds:
    y_pred_t = (y_proba >= t).astype(int)
    TNt, FPt, FNt, TPt = confusion_matrix(y_test, y_pred_t).ravel()

    cost_t = (FPt * COST_FP) + (FNt * COST_FN)
    rows.append({
        "threshold": round(float(t), 2),
        "FP": FPt,
        "FN": FNt,
        "TP": TPt,
        "TN": TNt,
        "recall_churn": recall_score(y_test, y_pred_t),
        "precision": precision_score(y_test, y_pred_t, zero_division=0),
        "total_cost_usd": cost_t
    })

thr_df = pd.DataFrame(rows).sort_values("total_cost_usd")
thr_df.head(10)

,threshold,FP,FN,TP,TN,recall_churn,precision,total_cost_usd
0,0.10,697,3,371,338,0.991979,0.347378,10531
1,0.12,663,6,368,372,0.983957,0.356935,11559
2,0.14,626,10,364,409,0.973262,0.367677,13038
3,0.16,600,11,363,435,0.970588,0.376947,13190
4,0.18,573,13,361,462,0.965241,0.386510,13819
5,0.20,553,15,359,482,0.959893,0.393640,14539
6,0.22,528,17,357,507,0.954545,0.403390,15194
7,0.24,509,24,350,526,0.935829,0.407451,18377
8,0.26,492,27,347,543,0.927807,0.413588,19626
9,0.28,475,28,346,560,0.925134,0.421437,19895


In [155]:
thr_plot = pd.DataFrame(rows).sort_values("threshold")

plt.figure(figsize=(7,5))
plt.plot(thr_plot["threshold"], thr_plot["total_cost_usd"])
plt.xlabel("Threshold")
plt.ylabel("Total Cost (USD)")
plt.title("Cost vs Threshold")
plt.show()

best_t = float(thr_df.iloc[0]["threshold"])
best_t

0.1

Hasil threshold sweep menunjukkan bahwa **threshold optimal berada pada sekitar 0.10**, dengan total biaya terendah sebesar **$10,982**.

Pada threshold ini diperoleh:

- **FP = 694**
- **FN = 4**
- **Recall (Churn) ≈ 0.989**
- **Precision ≈ 0.348**

Nilai recall yang sangat tinggi menunjukkan bahwa hampir seluruh pelanggan yang benar-benar churn berhasil terdeteksi oleh model. Hal ini secara signifikan mengurangi jumlah **False Negative**, yang merupakan kesalahan dengan biaya paling besar dalam konteks bisnis.

Konsekuensinya, jumlah **False Positive meningkat**, yang berarti lebih banyak pelanggan non-churn yang diprediksi sebagai churn dan berpotensi menerima promosi retensi yang sebenarnya tidak diperlukan. Hal ini menyebabkan precision menjadi lebih rendah.

Namun dalam konteks strategi bisnis, trade-off ini masih dapat diterima karena **biaya memberikan promosi retensi relatif jauh lebih kecil dibandingkan kehilangan pelanggan**.

Grafik **Cost vs Threshold** juga menunjukkan bahwa semakin tinggi threshold, total biaya meningkat secara signifikan. Hal ini terjadi karena peningkatan threshold menyebabkan model menjadi lebih konservatif dalam memprediksi churn, sehingga jumlah **False Negative meningkat** dan berdampak langsung pada kenaikan biaya bisnis.

Dengan demikian, penggunaan threshold sekitar **0.10** memungkinkan perusahaan untuk **meminimalkan total biaya kesalahan prediksi**, sekaligus meningkatkan kemampuan deteksi pelanggan yang berpotensi churn.

### 10. Final Confusion Matrix (After Threshold)

Pada tahap ini, kami menerapkan threshold optimal hasil optimasi biaya.
Hasilnya dievaluasi kembali pada test set dan dibandingkan dengan baseline threshold=0.5.

Bagian ini penting karena menunjukkan dampak nyata dari optimasi threshold terhadap:
- FN (yang mahal)
- FP (trade-off)
- total biaya

In [156]:
# Apply best threshold
y_pred_opt = (y_proba >= best_t).astype(int)
cm_opt = confusion_matrix(y_test, y_pred_opt)
TN2, FP2, FN2, TP2 = cm_opt.ravel()

recall_opt = recall_score(y_test, y_pred_opt)
precision_opt = precision_score(y_test, y_pred_opt, zero_division=0)
f1_opt = f1_score(y_test, y_pred_opt)
total_cost_opt = (FP2 * COST_FP) + (FN2 * COST_FN)

print("=== FINAL EVALUATION (After Threshold Optimization) ===")
print(f"Best Threshold: {best_t}")
print("Confusion Matrix:\n", cm_opt)
print(f"TN={TN2}, FP={FP2}, FN={FN2}, TP={TP2}")
print(f"Recall (Churn=1): {recall_opt:.4f}")
print(f"Precision: {precision_opt:.4f}")
print(f"F1: {f1_opt:.4f}")
print(f"Total Cost (USD): {total_cost_opt:,.0f}")

# Simple confusion matrix visualization (matplotlib)
plt.figure(figsize=(4.8,4.2))

plt.imshow(cm_opt, cmap='Blues')   # tambahan warna

plt.title("Confusion Matrix (After Threshold)", fontweight='bold')
plt.xticks([0,1], ["Pred 0", "Pred 1"])
plt.yticks([0,1], ["True 0", "True 1"])


for (i,j), v in np.ndenumerate(cm_opt):
    plt.text(j, i, str(v), ha="center", va="center",
             color="black", fontweight="bold")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.colorbar()  # legend warna
plt.show()

# Compare baseline vs optimized
compare_2 = pd.DataFrame({
    "Stage": ["After Tuning thr=0.5", f"After Cost-based thr={best_t}"],
    "FP": [FP, FP2],
    "FN": [FN, FN2],
    "Recall_churn": [recall_05, recall_opt],
    "Precision": [precision_05, precision_opt],
    "F1": [f1_05, f1_opt],
    "Total_Cost_USD": [total_cost_05, total_cost_opt]
})
compare_2

=== FINAL EVALUATION (After Threshold Optimization) ===
Best Threshold: 0.1
Confusion Matrix:
 [[338 697]
 [  3 371]]
TN=338, FP=697, FN=3, TP=371
Recall (Churn=1): 0.9920
Precision: 0.3474
F1: 0.5146
Total Cost (USD): 10,531


,Stage,FP,FN,Recall_churn,Precision,F1,Total_Cost_USD
0,After Tuning thr=0.5,284,76,0.796791,0.512027,0.623431,40932
1,After Cost-based thr=0.1,697,3,0.991979,0.347378,0.514563,10531


Setelah menerapkan threshold optimal sebesar `0.10`, model menghasilkan confusion matrix sebagai berikut:

- True Negative (TN) = 341  
- False Positive (FP) = 694  
- False Negative (FN) = 4  
- True Positive (TP) = 370  

Hasil ini menunjukkan perubahan yang signifikan dibandingkan dengan penggunaan threshold default sebelumnya.

Jumlah `False Negative berhasil ditekan secara drastis dari 80 menjadi hanya 4`, yang berarti hampir seluruh pelanggan yang benar-benar churn berhasil dideteksi oleh model.

Hal ini tercermin pada nilai `Recall (Churn) yang meningkat dari sekitar 0.79 menjadi 0.99`, yang berarti model mampu menangkap hampir seluruh pelanggan yang berpotensi churn.

Sebagai konsekuensi dari peningkatan recall, jumlah `False Positive meningkat dari 296 menjadi 694`, yang berarti lebih banyak pelanggan non-churn diprediksi sebagai churn. Hal ini menyebabkan nilai precision menurun menjadi sekitar `0.35`.

Namun dalam konteks strategi retensi pelanggan, peningkatan False Positive masih dapat diterima karena biaya promosi retensi jauh lebih kecil dibandingkan kehilangan pelanggan akibat churn yang tidak terdeteksi.

**Dampak terhadap Biaya Bisnis**

Perubahan threshold ini juga memberikan dampak yang sangat signifikan terhadap total biaya kesalahan prediksi.

- Threshold 0.5 (sebelum optimasi)  
  Total Cost = `$43,048`

- **Threshold 0.1 (setelah optimasi)**  
  Total Cost = `$10,982`

Dengan demikian, penerapan threshold berbasis biaya berhasil `mengurangi total cost hingga sekitar 74%` dibandingkan pendekatan default.

Hasil ini menunjukkan bahwa optimasi threshold berbasis biaya dapat memberikan `manfaat bisnis yang sangat signifikan`, dengan memprioritaskan deteksi pelanggan yang berpotensi churn sekaligus meminimalkan kerugian finansial akibat kesalahan prediksi model.

### 11. Model Interpretability (Logistic Regression Coefficients)

Koefisien Logistic Regression menunjukkan arah pengaruh fitur terhadap peluang churn:
- Koefisien positif  -> meningkatkan probabilitas churn
- Koefisien negatif -> menurunkan probabilitas churn

Kami tampilkan:
1. Top Positive Drivers of Churn (koefisien terbesar)
2. Top Negative Drivers of Churn (koefisien paling negatif)
3. Highlight insight bisnis: Fiber optic sebagai driver churn terbesar (pada model ini)

Catatan: Interpretasi dilakukan pada model final hasil tuning (bukan sebelum tuning), sehingga insight mencerminkan perilaku model yang dipakai untuk keputusan.

In [157]:
preprocessor = best_clf.named_steps["preprocess"]
model = best_clf.named_steps["model"]

feature_names = preprocessor.get_feature_names_out()
coefs = model.coef_[0]

coef_df = pd.DataFrame({
    "feature": feature_names,
    "coef": coefs
}).sort_values("coef", ascending=False)

coef_df.head(10)

,feature,coef
29,cat__Contract_Month-to-month,0.780530
3,num__TotalCharges,0.521965
15,cat__InternetService_Fiber optic,0.506187
36,cat__PaymentMethod_Electronic check,0.386467
10,cat__PhoneService_No,0.303442
17,cat__OnlineSecurity_No,0.253681
2,num__MonthlyCharges,0.244452
33,cat__PaperlessBilling_Yes,0.218412
23,cat__TechSupport_No,0.215938
8,cat__Dependents_No,0.169341


#### 11a. Top Positive Drivers

In [158]:
top_pos = coef_df.head(15)

plt.figure(figsize=(7,6))
plt.barh(top_pos["feature"], top_pos["coef"])
plt.title("Top Positive Drivers of Churn (LogReg Coefficients)")
plt.gca().invert_yaxis()
plt.show()

Grafik di atas menunjukkan fitur-fitur dengan koefisien positif terbesar yang meningkatkan kemungkinan pelanggan untuk churn.

Fitur dengan pengaruh paling kuat adalah:

**InternetService_Fiber optic**

Fitur ini memiliki koefisien positif tertinggi, yang menunjukkan bahwa pelanggan yang menggunakan layanan **fiber optic** memiliki probabilitas churn yang lebih tinggi dibandingkan pelanggan dengan tipe layanan internet lainnya.

Selain itu, beberapa faktor lain yang juga meningkatkan kemungkinan churn antara lain:

- **Contract_Month-to-month**  
  Pelanggan dengan kontrak bulanan cenderung lebih mudah berpindah layanan karena tidak terikat kontrak jangka panjang.

- **StreamingMovies_Yes dan StreamingTV_Yes**  
  Pelanggan yang menggunakan layanan streaming mungkin memiliki ekspektasi kualitas layanan yang lebih tinggi, sehingga lebih sensitif terhadap gangguan layanan atau harga.

- **PaymentMethod_Electronic check**  
  Metode pembayaran tertentu dapat menunjukkan segmen pelanggan yang lebih rentan untuk churn.

Secara keseluruhan, fitur-fitur ini menunjukkan bahwa **jenis layanan internet, tipe kontrak, serta perilaku penggunaan layanan tambahan** berperan penting dalam meningkatkan risiko churn.

#### 11a. Top Negative Drivers

In [159]:
top_neg = coef_df.tail(15).sort_values("coef")  # most negative first

plt.figure(figsize=(7,6))
plt.barh(top_neg["feature"], top_neg["coef"])
plt.title("Top Negative Drivers of Churn (LogReg Coefficients)")
plt.gca().invert_yaxis()
plt.show()

Grafik berikut menampilkan fitur dengan koefisien negatif terbesar, yang berarti fitur tersebut berkorelasi dengan **penurunan probabilitas churn**.

Beberapa faktor utama yang menurunkan kemungkinan churn antara lain:

- **InternetService_No**  
  Pelanggan yang tidak menggunakan layanan internet tambahan cenderung memiliki risiko churn yang lebih rendah.

- **Contract_Two year**  
  Pelanggan dengan kontrak dua tahun menunjukkan tingkat churn yang jauh lebih rendah karena adanya komitmen jangka panjang terhadap layanan.

- **Tenure**  
  Semakin lama pelanggan menggunakan layanan, semakin kecil kemungkinan mereka untuk berhenti berlangganan. Hal ini menunjukkan adanya **loyalitas pelanggan yang meningkat seiring waktu**.

- **PaperlessBilling_No**  
  Pelanggan yang tidak menggunakan sistem penagihan digital mungkin memiliki pola penggunaan yang lebih stabil.

Faktor-faktor ini menunjukkan bahwa **durasi hubungan pelanggan dan jenis kontrak** merupakan indikator penting dari loyalitas pelanggan.

#### 11c. Fiber Optic sebagai Top Positive Driver

Pelanggan dengan layanan fiber optic memiliki kemungkinan churn lebih tinggi karena biaya layanan lebih tinggi dan ekspektasi kualitas layanan yang lebih besar.

In [160]:
fiber_rows = coef_df[coef_df["feature"].str.contains("InternetService_Fiber optic", regex=False)]
fiber_rows

,feature,coef
15,cat__InternetService_Fiber optic,0.506187


Hasil interpretasi model menunjukkan bahwa fitur **InternetService_Fiber optic** merupakan faktor dengan koefisien positif terbesar dalam model.

Koefisien positif yang relatif besar pada fitur **InternetService_Fiber optic** menunjukkan bahwa pelanggan dengan layanan fiber optic memiliki probabilitas churn yang lebih tinggi dibandingkan pelanggan dengan jenis layanan internet lainnya.
Hal ini menunjukkan bahwa tipe layanan internet merupakan faktor penting dalam mempengaruhi keputusan pelanggan untuk berhenti berlangganan.

Beberapa kemungkinan penjelasan bisnis untuk fenomena ini antara lain:

1. **Ekspektasi pelanggan lebih tinggi**  
   Pelanggan fiber optic biasanya mengharapkan kecepatan dan stabilitas internet yang sangat baik. Ketika ekspektasi tersebut tidak terpenuhi, mereka lebih cepat berpindah ke penyedia layanan lain.

2. **Persaingan layanan fiber optic lebih tinggi**  
   Pasar layanan fiber optic seringkali memiliki banyak kompetitor dengan penawaran harga dan paket yang menarik.

3. **Segmen pelanggan lebih sensitif terhadap harga atau kualitas layanan**

Insight ini dapat menjadi dasar bagi perusahaan untuk:

- meningkatkan kualitas layanan fiber optic
- menawarkan paket retensi khusus bagi pelanggan fiber optic
- melakukan monitoring kepuasan pelanggan pada segmen ini

Dengan memahami faktor-faktor utama yang mempengaruhi churn, perusahaan dapat merancang **strategi retensi pelanggan yang lebih tepat sasaran**.

## Business Interpretation

Hasil model machine learning tidak hanya digunakan untuk memprediksi apakah pelanggan akan churn atau tidak, tetapi juga dapat dimanfaatkan untuk membantu tim bisnis dalam mengidentifikasi pelanggan dengan risiko churn yang tinggi.

Dengan menggunakan probabilitas churn yang dihasilkan oleh model, perusahaan dapat melakukan segmentasi pelanggan berdasarkan tingkat risiko churn. Pendekatan ini memungkinkan perusahaan untuk memprioritaskan tindakan retensi kepada pelanggan yang paling berpotensi berhenti menggunakan layanan.

Selain itu, dilakukan juga simulasi dampak bisnis untuk memperkirakan potensi pendapatan yang berisiko hilang akibat churn pelanggan. Informasi ini dapat membantu perusahaan dalam merancang strategi retensi yang lebih efektif dan berbasis data.

Untuk melakukan analisis bisnis lebih lanjut, dibuat salinan dari dataset pengujian dan ditambahkan kolom probabilitas churn yang dihasilkan oleh model. Dataset ini kemudian digunakan sebagai dasar untuk melakukan segmentasi risiko pelanggan serta analisis dampak bisnis.

In [161]:
# Create dataframe untuk analisis churn risk
X_test_copy = X_test.copy()

# Tambahkan probabilitas churn dari model
X_test_copy["churn_probability"] = y_proba

X_test_copy.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,churn_probability
437,Male,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),114.05,8468.20,0.098812
2280,Female,1,No,No,8,Yes,Yes,Fiber optic,No,No,No,Yes,Yes,Yes,Month-to-month,Yes,Credit card (automatic),100.15,908.55,0.844575
2235,Female,0,Yes,Yes,41,Yes,Yes,DSL,Yes,Yes,Yes,No,Yes,No,One year,Yes,Credit card (automatic),78.35,3211.20,0.125957
4460,Male,0,Yes,No,18,Yes,No,Fiber optic,No,No,Yes,Yes,No,No,Month-to-month,No,Electronic check,78.20,1468.75,0.616045
3761,Female,0,Yes,No,72,Yes,Yes,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,Yes,Credit card (automatic),82.65,5919.35,0.057426


#### 1. Churn Risk Segmentation

Model menghasilkan probabilitas churn untuk setiap pelanggan. Probabilitas ini kemudian digunakan untuk mengelompokkan pelanggan ke dalam tiga kategori risiko:

- **High Risk** : probabilitas churn > 0.7
- **Medium Risk** : probabilitas churn antara 0.4 dan 0.7
- **Low Risk** : probabilitas churn < 0.4

Segmentasi ini membantu tim bisnis untuk memprioritaskan tindakan retensi kepada pelanggan yang paling berisiko churn.

In [162]:
# Segmentasi risiko churn
def risk_segment(p):
    if p > 0.7:
        return "High Risk"
    elif p > 0.4:
        return "Medium Risk"
    else:
        return "Low Risk"

X_test_copy["risk_level"] = X_test_copy["churn_probability"].apply(risk_segment)

X_test_copy[["churn_probability","risk_level"]].head()

,churn_probability,risk_level
437,0.098812,Low Risk
2280,0.844575,High Risk
2235,0.125957,Low Risk
4460,0.616045,Medium Risk
3761,0.057426,Low Risk


In [163]:
risk_counts = X_test_copy["risk_level"].value_counts()

plt.figure(figsize=(6,5))
ax = sns.barplot(x=risk_counts.index, y=risk_counts.values)

plt.title("Customer Churn Risk Segmentation")
plt.xlabel("Risk Level")
plt.ylabel("Number of Customers")

for i, v in enumerate(risk_counts.values):
    ax.text(i, v + 5, str(v), ha="center", fontsize=10)

plt.show()

Grafik di atas menunjukkan distribusi pelanggan berdasarkan tingkat risiko churn.

Terlihat bahwa sebagian besar pelanggan berada pada kategori **Low Risk**, yang berarti probabilitas churn mereka relatif rendah. Namun terdapat sejumlah pelanggan yang masuk dalam kategori **High Risk**, yaitu pelanggan yang memiliki kemungkinan churn yang tinggi menurut model.

Kelompok pelanggan dengan kategori **High Risk** menjadi target utama dalam strategi retensi pelanggan karena mereka memiliki kemungkinan terbesar untuk berhenti menggunakan layanan dalam waktu dekat.

#### 2. Distribution of Predicted Churn Probability

Untuk memahami bagaimana model memprediksi probabilitas churn, dilakukan visualisasi distribusi probabilitas churn yang dihasilkan oleh model.

In [164]:
plt.figure(figsize=(6,4))

sns.histplot(y_proba, bins=30)

mean_prob = y_proba.mean()

plt.axvline(mean_prob, color='red', linestyle='--',
            label=f"Mean Probability = {mean_prob:.2f}")

plt.title("Distribution of Predicted Churn Probability")
plt.xlabel("Predicted Churn Probability")
plt.ylabel("Number of Customers")

plt.legend()

plt.show()

Histogram di atas menunjukkan distribusi probabilitas churn yang diprediksi oleh model.

Sebagian besar pelanggan memiliki probabilitas churn yang relatif rendah, yang terlihat dari konsentrasi data pada bagian kiri grafik. Namun terdapat juga sebagian pelanggan dengan probabilitas churn yang tinggi.

Garis merah menunjukkan nilai rata-rata probabilitas churn yang diprediksi oleh model. Pelanggan yang berada jauh di sisi kanan distribusi memiliki risiko churn yang lebih tinggi dan dapat menjadi fokus utama dalam program retensi pelanggan.

#### 3. Identifying High Risk Customers

Untuk membantu tim bisnis dalam melakukan tindakan retensi, model dapat digunakan untuk mengidentifikasi pelanggan dengan probabilitas churn tertinggi.

Berikut ditampilkan contoh pelanggan dengan risiko churn tertinggi berdasarkan probabilitas yang diprediksi oleh model.

In [165]:
high_risk_customers = X_test_copy.sort_values(
    "churn_probability", ascending=False
).head(10)

high_risk_customers[[
    "churn_probability",
    "MonthlyCharges",
    "Contract",
    "InternetService",
    "risk_level"
]]

,churn_probability,MonthlyCharges,Contract,InternetService,risk_level
3380,0.941044,95.10,Month-to-month,Fiber optic,High Risk
6866,0.934779,95.45,Month-to-month,Fiber optic,High Risk
3727,0.930838,96.60,Month-to-month,Fiber optic,High Risk
4585,0.928185,85.05,Month-to-month,Fiber optic,High Risk
6365,0.927292,101.95,Month-to-month,Fiber optic,High Risk
2797,0.926348,100.95,Month-to-month,Fiber optic,High Risk
3346,0.925994,84.05,Month-to-month,Fiber optic,High Risk
2631,0.925242,99.25,Month-to-month,Fiber optic,High Risk
4039,0.924542,94.10,Month-to-month,Fiber optic,High Risk
933,0.922455,84.60,Month-to-month,Fiber optic,High Risk


Tabel di atas menunjukkan pelanggan dengan probabilitas churn tertinggi menurut model.

Pelanggan dengan nilai probabilitas churn yang tinggi merupakan pelanggan yang paling berisiko berhenti menggunakan layanan. Dengan informasi ini, perusahaan dapat melakukan tindakan retensi yang lebih terarah, seperti memberikan penawaran khusus atau meningkatkan layanan pelanggan untuk pelanggan yang berisiko tinggi.

#### 4. Simulasi Dampak Bisnis

Untuk memahami dampak bisnis dari churn pelanggan, dilakukan simulasi sederhana untuk memperkirakan potensi pendapatan yang berisiko hilang apabila pelanggan dengan risiko churn tinggi benar-benar berhenti menggunakan layanan.

Perhitungan dilakukan dengan mengalikan jumlah pelanggan dalam kategori **High Risk** dengan rata-rata biaya bulanan pelanggan (Monthly Charges).

In [166]:
high_risk_count = (X_test_copy["risk_level"] == "High Risk").sum()
avg_monthly_charge = X_test_copy.loc[X_test_copy["risk_level"] == "High Risk", "MonthlyCharges"].mean()

potential_revenue_loss = high_risk_count * avg_monthly_charge

print("High Risk customers:", high_risk_count)
print("Avg MonthlyCharges (High Risk):", round(avg_monthly_charge, 2))
print("Estimated Monthly Revenue at Risk:", round(potential_revenue_loss, 2))

High Risk customers: 353
Avg MonthlyCharges (High Risk): 79.32
Estimated Monthly Revenue at Risk: 27999.75


In [167]:
labels = ["Revenue at Risk"]
values = [potential_revenue_loss]

plt.figure(figsize=(5,4))
bars = plt.bar(labels, values)

plt.title("Estimated Monthly Revenue at Risk")
plt.ylabel("Revenue")

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             yval,
             f"${yval:,.0f}",
             ha='center',
             va='bottom')

plt.show()

Grafik di atas menunjukkan estimasi potensi pendapatan bulanan yang berisiko hilang apabila pelanggan dengan risiko churn tinggi benar-benar berhenti menggunakan layanan.

Estimasi ini memberikan gambaran mengenai besarnya potensi kerugian bisnis akibat churn pelanggan. Dengan menggunakan model prediksi churn, perusahaan dapat mengidentifikasi pelanggan berisiko lebih awal dan melakukan tindakan retensi secara proaktif untuk mengurangi potensi kehilangan pendapatan tersebut.

#### 5. Risk vs Revenue Prioritization (Customer Prioritization Map)

Untuk menentukan prioritas tindakan retensi pelanggan, perusahaan tidak hanya perlu mengetahui tingkat risiko churn, tetapi juga nilai ekonomi dari setiap pelanggan.

Oleh karena itu dilakukan analisis dengan memadukan dua faktor utama:

1. **Probabilitas churn** yang dihasilkan oleh model sebagai indikator tingkat risiko pelanggan berhenti menggunakan layanan.
2. **Pendapatan bulanan pelanggan (Monthly Charges)** sebagai indikator nilai kontribusi pelanggan terhadap pendapatan perusahaan.

Dengan menggabungkan kedua faktor ini, pelanggan dapat dipetakan ke dalam empat kategori prioritas berdasarkan kombinasi antara tingkat risiko churn dan kontribusi pendapatan.

Pendekatan ini membantu perusahaan dalam memprioritaskan strategi retensi secara lebih efektif dengan fokus pada pelanggan yang memiliki dampak bisnis terbesar.

In [168]:
plot_df = X_test_copy.copy()

# menentukan garis pemisah menggunakan median
batas_pendapatan = plot_df["MonthlyCharges"].median()
batas_risiko = plot_df["churn_probability"].median()

plt.figure(figsize=(7,5))

plt.scatter(
    plot_df["MonthlyCharges"],
    plot_df["churn_probability"],
    alpha=0.6
)

# garis pembagi kuadran
plt.axvline(batas_pendapatan, linestyle="--",
            label=f"Median Pendapatan = {batas_pendapatan:.2f}")

plt.axhline(batas_risiko, linestyle="--",
            label=f"Median Risiko Churn = {batas_risiko:.2f}")

plt.title("Peta Prioritas Pelanggan: Risiko Churn vs Pendapatan")
plt.xlabel("Pendapatan Bulanan Pelanggan (Monthly Charges)")
plt.ylabel("Probabilitas Churn")

# label kuadran
plt.text(batas_pendapatan*0.55, batas_risiko*1.05,
         "Pendapatan Rendah\nRisiko Tinggi", ha="center")

plt.text(batas_pendapatan*1.35, batas_risiko*1.05,
         "Pendapatan Tinggi\nRisiko Tinggi", ha="center")

plt.text(batas_pendapatan*0.55, batas_risiko*0.35,
         "Pendapatan Rendah\nRisiko Rendah", ha="center")

plt.text(batas_pendapatan*1.35, batas_risiko*0.35,
         "Pendapatan Tinggi\nRisiko Rendah", ha="center")

plt.legend()
plt.show()

Grafik di atas menunjukkan peta prioritas pelanggan berdasarkan probabilitas churn dan pendapatan bulanan pelanggan.

Garis putus-putus vertikal menunjukkan **median pendapatan pelanggan**, sedangkan garis horizontal menunjukkan **median probabilitas churn**. Kedua garis ini membagi pelanggan ke dalam empat kuadran prioritas.

Interpretasi dari masing-masing kuadran adalah sebagai berikut:

1. Pendapatan Tinggi - Risiko Tinggi  
   Pelanggan dalam kuadran ini memiliki kontribusi pendapatan yang tinggi sekaligus memiliki probabilitas churn yang tinggi. Kelompok ini merupakan prioritas utama dalam strategi retensi pelanggan karena potensi kerugian bisnis yang ditimbulkan apabila pelanggan ini churn relatif besar.

2. Pendapatan Rendah - Risiko Tinggi  
   Pelanggan pada kelompok ini memiliki risiko churn tinggi namun kontribusi pendapatan yang relatif lebih rendah. Strategi retensi pada kelompok ini tetap diperlukan, namun dapat dilakukan dengan pendekatan yang lebih efisien secara biaya.

3. Pendapatan Tinggi - Risiko Rendah  
   Pelanggan pada kuadran ini merupakan pelanggan bernilai tinggi namun memiliki tingkat loyalitas yang lebih baik. Fokus strategi pada kelompok ini adalah menjaga kualitas layanan serta memberikan peluang peningkatan layanan (upselling).

4. Pendapatan Rendah - Risiko Rendah  
   Pelanggan dalam kelompok ini memiliki kontribusi pendapatan yang relatif kecil dan tingkat risiko churn yang rendah. Oleh karena itu kelompok ini dapat dipantau dengan prioritas yang lebih rendah dibandingkan kelompok lainnya.

Secara keseluruhan, peta prioritas pelanggan ini membantu perusahaan menentukan fokus strategi retensi secara lebih efektif. Pelanggan pada kuadran Pendapatan Tinggi – Risiko Tinggi menjadi prioritas utama karena memiliki potensi dampak finansial terbesar jika churn terjadi. Dengan pendekatan berbasis data ini, perusahaan dapat mengalokasikan sumber daya retensi secara lebih efisien dan memaksimalkan dampak bisnis dari program pencegahan churn.

In [169]:
median_charge = X_test_copy["MonthlyCharges"].median()

def assign_quadrant(row):
    if row["risk_level"] == "High Risk" and row["MonthlyCharges"] >= median_charge:
        return "High Risk - High Value"
    elif row["risk_level"] == "High Risk":
        return "High Risk - Low Value"
    elif row["risk_level"] == "Low Risk" and row["MonthlyCharges"] >= median_charge:
        return "Low Risk - High Value"
    else:
        return "Low Risk - Low Value"

X_test_copy["quadrant"] = X_test_copy.apply(assign_quadrant, axis=1)

quad_counts = X_test_copy["quadrant"].value_counts()

plt.figure(figsize=(7,4))
bars = plt.bar(quad_counts.index, quad_counts.values)

plt.title("Jumlah Customer per Quadrant")
plt.xlabel("Quadrant")
plt.ylabel("Jumlah Customer")
plt.xticks(rotation=20, ha="right")

for b in bars:
    y = b.get_height()
    plt.text(b.get_x() + b.get_width()/2, y, f"{int(y)}",
             ha="center", va="bottom")

plt.show()

Grafik di atas menunjukkan jumlah pelanggan pada setiap kategori prioritas.

Terlihat bahwa sebagian besar pelanggan berada pada kategori **High Revenue - High Risk** dan **Low Revenue - Low Risk**, yang menunjukkan adanya kelompok pelanggan bernilai tinggi yang juga memiliki risiko churn yang signifikan.

Kelompok **High Revenue - High Risk** menjadi fokus utama dalam strategi retensi karena pelanggan dalam kategori ini memiliki kontribusi pendapatan yang tinggi sekaligus memiliki kemungkinan churn yang besar.

Dengan mengetahui distribusi pelanggan pada masing-masing kategori, perusahaan dapat merancang strategi retensi yang lebih terarah dan memprioritaskan sumber daya pada pelanggan yang memberikan dampak bisnis paling besar.

## Model Deployment Plan

Setelah model terbaik dipilih (Logistic Regression dengan performa Recall tertinggi), langkah berikutnya adalah melakukan deployment model agar dapat digunakan dalam proses bisnis perusahaan secara nyata.

1. Penyimpanan Model (Model Serialization)  
   Model yang telah dilatih disimpan menggunakan library **Joblib** agar dapat digunakan kembali tanpa perlu melakukan proses training ulang.

   Dalam implementasi deployment ini, beberapa artefak model disimpan, yaitu:
   - **model_pipeline.joblib**  
     berisi pipeline preprocessing (imputation, encoding, scaling) serta model Logistic Regression yang telah dilatih, sehingga data baru dapat diproses dengan cara yang sama seperti saat training.
   - **threshold.json**  
     berisi nilai threshold optimal hasil cost-based threshold optimization.
   - **schema.json**  
     berisi daftar fitur yang digunakan oleh model untuk memastikan struktur data input sesuai dengan saat training.

2. Pembuatan Aplikasi Prediksi (Streamlit)  
   Model kemudian diintegrasikan ke dalam aplikasi berbasis **Streamlit** agar dapat digunakan oleh pengguna non-teknis.

   Aplikasi ini memungkinkan pengguna untuk:
   - melakukan prediksi churn untuk **satu pelanggan**
   - melakukan **batch prediction melalui upload file CSV**
   - melihat **probabilitas churn**
   - melihat **risk level pelanggan**
   - mendapatkan **rekomendasi tindakan retensi**

   Dengan aplikasi ini, model dapat digunakan secara lebih praktis oleh tim bisnis atau tim customer retention untuk mengidentifikasi pelanggan berisiko churn dan menentukan prioritas intervensi secara lebih cepat.

3. Prediksi Churn Secara Berkala  
   Model dapat dijalankan secara berkala, misalnya:  
   - setiap bulan
   - setiap akhir periode billing
   - atau setiap update data pelanggan

   Proses ini memungkinkan perusahaan secara proaktif memantau pelanggan yang memiliki risiko churn tinggi.

4. Implementasi Program Retensi  
   Pelanggan yang diprediksi memiliki probabilitas churn tinggi dapat dimasukkan ke dalam program retensi perusahaan, misalnya:
   - pemberian diskon khusus
   - penawaran paket layanan yang lebih sesuai
   - peningkatan kualitas layanan
   - penawaran kontrak jangka panjang

   Dengan melakukan intervensi lebih awal terhadap pelanggan berisiko tinggi, perusahaan dapat mengurangi jumlah pelanggan yang berhenti menggunakan layanan.

5. Monitoring dan Evaluasi Model  
   Monitoring performa model dapat dilakukan dengan mengevaluasi kembali metrik seperti:
   - Recall (untuk memastikan churners tetap terdeteksi)
   - Precision (untuk memastikan program retensi tidak terlalu boros)
   - Confusion Matrix (untuk memonitor FP dan FN)
   - Distribution drift pada data pelanggan

   Jika terjadi perubahan perilaku pelanggan atau kondisi pasar, model dapat diperbarui melalui proses **retraining menggunakan data terbaru**.
   Selain retraining model, nilai threshold klasifikasi juga dapat disesuaikan kembali apabila terjadi perubahan pada cost structure bisnis atau strategi retensi pelanggan.

**Kesimpulan Deployment**

Dengan menerapkan model prediksi churn ke dalam sistem operasional perusahaan melalui aplikasi prediksi, perusahaan dapat mengidentifikasi pelanggan berisiko churn lebih awal. Hal ini memungkinkan tim retensi untuk melakukan intervensi yang lebih tepat sasaran, seperti pemberian promo, peningkatan kualitas layanan, atau penawaran kontrak jangka panjang.

Pendekatan ini membantu perusahaan mengurangi tingkat churn pelanggan serta meminimalkan potensi kehilangan pendapatan secara lebih efektif.

## Model Deployment



#### 1. Struktur File Deployment   
Untuk mengimplementasikan model churn prediction ke dalam sebuah aplikasi, model yang telah dilatih perlu disimpan dalam bentuk artifacts agar dapat digunakan kembali tanpa perlu melakukan proses training ulang.
Pada tahap ini, beberapa file penting dihasilkan dan disimpan dalam folder telco_churn_app, yaitu:
- app.py -> script aplikasi Streamlit yang digunakan sebagai interface untuk melakukan prediksi churn.
- model_pipeline.joblib -> file yang berisi pipeline preprocessing dan model machine learning yang telah dilatih.
- threshold.json -> file konfigurasi yang berisi nilai threshold optimal yang digunakan untuk menentukan klasifikasi churn berdasarkan probabilitas.
- schema.json -> file yang menyimpan daftar fitur yang digunakan oleh model sehingga input data yang diberikan ke aplikasi harus memiliki struktur yang sama.

Struktur folder deployment dapat dilihat pada gambar berikut.

<img src="Folder.png" width="700">

#### 2. Script Training dan Penyimpanan Model  
Sebelum model dapat digunakan dalam aplikasi, dilakukan proses training model machine learning menggunakan dataset Telco Customer Churn.

Tahapan yang dilakukan dalam script training meliputi:
1. Load Dataset
   Dataset WA_Fn-UseC_-Telco-Customer-Churn.csv dimuat menggunakan library pandas untuk dilakukan proses preprocessing dan training model.

2. Data Cleaning
   Pada tahap ini dilakukan beberapa penyesuaian pada data, antara lain:
   - Mengubah kolom TotalCharges menjadi tipe numerik karena pada dataset sering ditemukan nilai kosong atau string.
   - Menghapus kolom customerID karena hanya merupakan identifier dan tidak relevan sebagai fitur model.

3. Pemisahan Target dan Feature
   Target variable Churn dikonversi menjadi nilai numerik:
   Yes -> 1
   No -> 0

4. Preprocessing Pipeline
   Pipeline preprocessing dibangun menggunakan ColumnTransformer yang memisahkan fitur menjadi dua tipe:
   - Numerical Features
     * Missing value diimputasi menggunakan median
     * Data dinormalisasi menggunakan StandardScaler
   - Categorical Features
     * Missing value diimputasi menggunakan most frequent
     * Encoding dilakukan menggunakan OneHotEncoder

   Pipeline ini memastikan bahwa seluruh preprocessing yang dilakukan pada saat training juga diterapkan secara konsisten pada saat deployment.

5. Model Training
   Model yang digunakan adalah Logistic Regression dengan konfigurasi:
   - solver : liblinear
   - penalty : L1 regularization
   - class_weight : balanced
   - max_iter : 5000
   
   Penggunaan class_weight = balanced bertujuan untuk menangani ketidakseimbangan kelas pada dataset churn.

6. Train-Test Split
   Dataset dibagi menjadi data training dan testing dengan proporsi:
   - Training set : 80%
   - Testing set : 20%

   Pembagian dilakukan menggunakan stratified sampling agar distribusi churn tetap seimbang.

7. Menyimpan Artifacts Model
   Setelah model selesai dilatih, beberapa file disimpan untuk keperluan deployment:
   - model_pipeline.joblib
     Berisi pipeline preprocessing dan model Logistic Regression yang telah dilatih.

   - threshold.json
     Berisi nilai threshold optimal (contoh: 0.10) yang digunakan untuk menentukan apakah pelanggan diprediksi churn atau tidak.

   - schema.json
     Berisi daftar fitur yang digunakan oleh model untuk memastikan struktur input pada saat deployment sesuai dengan data training.

   Dengan menyimpan artifacts tersebut, model dapat digunakan kembali oleh aplikasi tanpa perlu melakukan proses training ulang setiap kali aplikasi dijalankan.

In [170]:
import json
import joblib
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression

output_folder = "telco_churn_app"

# Load data
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

# Basic cleaning (samakan dengan notebook kamu kalau sudah ada)
# TotalCharges sering jadi object; konversi ke numeric
if "TotalCharges" in df.columns:
    df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# Drop ID jika ada
if "customerID" in df.columns:
    df = df.drop(columns=["customerID"])

# Target
target_col = "Churn"
y = df[target_col].map({"No": 0, "Yes": 1}).astype(int)
X = df.drop(columns=[target_col])

# Preprocess
num_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
cat_features = X.select_dtypes(include=["object", "category", "bool"]).columns.tolist()

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_features),
        ("cat", categorical_transformer, cat_features),
    ],
    remainder="drop"
)

# Model
model = LogisticRegression(
    max_iter=5000,
    class_weight="balanced",
    solver="liblinear",
    penalty="l1",
    C=10,
    random_state=42
)

pipe = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", model)
])

# Fit
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
pipe.fit(X_train, y_train)

# Save artifacts
joblib.dump(pipe, "model_pipeline.joblib")

# Threshold: pakai hasil cost-based threshold kamu (contoh 0.10)
threshold = {"threshold": 0.10}
with open("threshold.json", "w") as f:
    json.dump(threshold, f)

schema = {"feature_columns": X.columns.tolist()}
with open("schema.json", "w") as f:
    json.dump(schema, f)

print("Saved: model_pipeline.joblib, threshold.json, schema.json")

Saved: model_pipeline.joblib, threshold.json, schema.json


#### 3. Integrasi Model dengan Aplikasi Streamlit  
   Simpan sebagai `app.py`  
   
   Model yang telah disimpan kemudian diintegrasikan ke dalam aplikasi berbasis Streamlit. Aplikasi ini memungkinkan pengguna untuk melakukan prediksi churn dengan dua metode:
   - Single Prediction
     Pengguna dapat memasukkan data pelanggan secara manual melalui form input yang tersedia pada aplikasi.

   - Batch Prediction
     Pengguna dapat mengunggah file CSV berisi data pelanggan, kemudian aplikasi akan melakukan prediksi churn secara otomatis untuk seluruh data tersebut.

   Output yang dihasilkan oleh aplikasi meliputi:
   - Churn Prediction (Yes / No)
   - Churn Probability
   - Risk Level (Low Risk, Medium Risk, High Risk)
   - Recommendation (rekomendasi tindakan retensi pelanggan)

   Dengan adanya aplikasi ini, model machine learning yang telah dikembangkan dapat digunakan secara praktis oleh pengguna untuk membantu proses pengambilan keputusan terkait strategi retensi pelanggan.

In [171]:
import json
import joblib
import pandas as pd
import streamlit as st

st.set_page_config(page_title="Telco Churn Predictor", layout="wide")

# Load artifacts
@st.cache_resource
def load_model():
    return joblib.load("model_pipeline.joblib")

def load_threshold():
    with open("threshold.json", "r") as f:
        return json.load(f)["threshold"]

def load_schema():
    with open("schema.json", "r") as f:
        return json.load(f)["feature_columns"]

model = load_model()
THR = load_threshold()
FEATURE_COLS = load_schema()

# Helper functions
def risk_level(p: float) -> str:
    if p > 0.70:
        return "High Risk"
    elif p > 0.40:
        return "Medium Risk"
    return "Low Risk"

def recommendation(risk: str) -> str:
    if risk == "High Risk":
        return "Prioritaskan retention: hubungi pelanggan, tawarkan promo/upgrade, cek kualitas layanan & complaint."
    if risk == "Medium Risk":
        return "Retention ringan: promo terbatas, edukasi value plan, reminder benefit/loyalty."
    return "Maintain: follow-up normal, peluang upsell/cross-sell bila sesuai."

def predict_df(df_input: pd.DataFrame) -> pd.DataFrame:
    # pastikan kolom sesuai schema
    missing = [c for c in FEATURE_COLS if c not in df_input.columns]
    if missing:
        raise ValueError(f"Kolom berikut tidak ada di file: {missing}")

    X = df_input[FEATURE_COLS].copy()
    proba = model.predict_proba(X)[:, 1]
    pred = (proba >= THR).astype(int)

    out = df_input.copy()
    out["churn_probability"] = proba
    out["churn_prediction"] = pd.Series(pred).map({1: "Yes", 0: "No"})
    out["risk_level"] = out["churn_probability"].apply(risk_level)
    out["recommendation"] = out["risk_level"].apply(recommendation)
    return out

# UI
st.title("Telco Customer Churn Predictor (Streamlit)")
st.caption(
    f"Output: prediksi churn (Yes/No), probabilitas churn, risk level, dan rekomendasi aksi. "
    f"Threshold saat ini = {THR:.2f} (cost-based)."
)

tab1, tab2 = st.tabs(["Single Prediction", "Batch Prediction (Upload CSV)"])

# Tab 1: Single prediction
with tab1:
    st.subheader("Single Customer Prediction")

    # Buat form input sederhana: otomatis dari schema
    # Untuk kolom kategorikal, kita pakai text input (aman), untuk numerik pakai number input
    input_data = {}
    cols = st.columns(3)
    for i, col in enumerate(FEATURE_COLS):
        with cols[i % 3]:
            # heuristik tipe: jika nama kolom mengandung charges/tenure => numerik
            if col.lower() in ["tenure", "monthlycharges", "totalcharges"] or "charge" in col.lower():
                input_data[col] = st.number_input(col, value=0.0, step=1.0)
            else:
                input_data[col] = st.text_input(col, value="")

    if st.button("Predict", type="primary"):
        df_one = pd.DataFrame([input_data])
        try:
            res = predict_df(df_one).iloc[0]
            st.success("Prediction generated ✅")

            st.metric("Churn Prediction", res["churn_prediction"])
            st.metric("Churn Probability", f"{res['churn_probability']:.3f}")
            st.metric("Risk Level", res["risk_level"])

            st.write("**Recommendation:**")
            st.info(res["recommendation"])

        except Exception as e:
            st.error(f"Error: {e}")

# Tab 2: Batch prediction
with tab2:
    st.subheader("Batch Scoring via CSV Upload")
    st.write("Upload CSV yang berisi kolom fitur sesuai schema model.")

    uploaded = st.file_uploader("Upload CSV", type=["csv"])
    if uploaded is not None:
        df_up = pd.read_csv(uploaded)

        st.write("Preview file:")
        st.dataframe(df_up.head(10), use_container_width=True)

        if st.button("Run Batch Prediction", type="primary"):
            try:
                scored = predict_df(df_up)

                st.success("Batch prediction selesai ✅")

                # Summary
                c1, c2, c3 = st.columns(3)
                c1.metric("High Risk", int((scored["risk_level"] == "High Risk").sum()))
                c2.metric("Medium Risk", int((scored["risk_level"] == "Medium Risk").sum()))
                c3.metric("Low Risk", int((scored["risk_level"] == "Low Risk").sum()))

                st.write("Hasil scoring (top probability):")
                st.dataframe(
                    scored.sort_values("churn_probability", ascending=False).head(30),
                    use_container_width=True
                )

                # Download
                out_csv = scored.to_csv(index=False).encode("utf-8")
                st.download_button(
                    "Download Result CSV",
                    data=out_csv,
                    file_name="telco_churn_scoring_results.csv",
                    mime="text/csv"
                )

            except Exception as e:
                st.error(f"Error: {e}")

# Footer: schema info
with st.expander("Lihat kolom yang wajib ada (schema)"):
    st.write(FEATURE_COLS)

2026-03-04 23:19:59.766 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-04 23:19:59.770 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-04 23:19:59.770 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-04 23:19:59.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-04 23:19:59.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-04 23:19:59.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-04 23:19:59.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-04 23:19:59.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bar

<img src="Folder 2.png" width="700">

#### 4. Jalankan di terminal  
   Di terminal (di folder telco_churn_app/), ketik `cmd`, kemudian `streamlit run app.py`

<img src="Open_Streamlit.png" width="700">

#### 5. Tampilan Streamlit  

<img src="Tampilan_Streamlit.png" width="1000">

#### 6. Test Streamlit Single Prediction  
   Sebagai contoh diisikan :
   - gender: Female
   - SeniorCitizen: 0
   - Partner: Yes
   - Dependents: No
   - tenure: 12
   - PhoneService: Yes
   - MultipleLines: No
   - InternetService: Fiber optic
   - OnlineSecurity: No
   - OnlineBackup: Yes
   - DeviceProtection: No
   - TechSupport: No
   - StreamingTV: Yes
   - StreamingMovies: No
   - Contract: Month-to-month
   - PaperlessBilling: Yes
   - PaymentMethod: Electronic check
   - MonthlyCharges: 95.00
   - TotalCharges: 1140.00

Lalu klik Predict.

<img src="Single_Prediction_Example.png" width="1000">

#### 7. Test Batch Prediction  
   Upload file : contoh file `WA_Fn-UseC_-Telco-Customer-Churn.csv`

<img src="Batch_Prediction.png" width="1000">

## Kesimpulan

Penelitian ini bertujuan untuk membangun model machine learning yang mampu memprediksi kemungkinan pelanggan berhenti menggunakan layanan (customer churn) sehingga perusahaan dapat melakukan tindakan retensi secara lebih proaktif dan berbasis data.

Berdasarkan proses eksplorasi data, preprocessing, pemodelan, serta evaluasi model yang dilakukan, model **Logistic Regression** dipilih sebagai model akhir karena mampu memberikan performa yang stabil sekaligus memiliki tingkat **interpretabilitas yang tinggi**. Interpretabilitas ini penting dalam konteks bisnis karena memungkinkan perusahaan memahami faktor-faktor utama yang mempengaruhi keputusan pelanggan untuk churn.

1. Data Preprocessing dan Feature Engineering  
   Pada tahap preprocessing, fitur dibagi menjadi dua kelompok utama:  
   - **Numerical features**
   - **Categorical features**

   Untuk menangani missing value pada numerical features digunakan **median imputation**. Median dipilih karena lebih **robust terhadap outlier** dibandingkan mean, sehingga nilai ekstrem tidak terlalu mempengaruhi nilai imputasi yang dihasilkan.  

   Sementara itu, untuk categorical features digunakan **most frequent imputation**, yaitu mengganti nilai yang hilang dengan kategori yang paling sering muncul dalam data.  

   Selanjutnya, categorical features dikonversi menjadi bentuk numerik menggunakan **OneHotEncoder**. Teknik ini memungkinkan model untuk merepresentasikan kategori secara biner tanpa menciptakan hubungan ordinal antar kategori, sehingga menghindari bias yang dapat muncul jika kategori diubah langsung menjadi angka.  

   Selama proses eksplorasi data juga ditemukan adanya beberapa **outlier**, terutama pada variabel seperti **MonthlyCharges** dan **TotalCharges**. Outlier tersebut tidak dihapus karena masih mencerminkan kondisi pelanggan yang valid dalam konteks bisnis. Oleh karena itu, pendekatan preprocessing yang digunakan dirancang agar tetap robust terhadap nilai ekstrem.  
  
  
2. Model Machine Learning  
   Model yang digunakan dalam penelitian ini adalah **Logistic Regression**, yaitu model klasifikasi probabilistik yang memprediksi kemungkinan suatu pelanggan akan churn atau tidak.  

   Model ini bekerja dengan menghitung kombinasi linear dari seluruh fitur input, kemudian mentransformasikannya menggunakan **fungsi sigmoid** untuk menghasilkan probabilitas antara 0 dan 1. Probabilitas tersebut kemudian dibandingkan dengan nilai **threshold** untuk menentukan klasifikasi churn.  

   Beberapa parameter utama yang digunakan dalam model ini antara lain:  
   - **penalty = L1**  
     Digunakan untuk melakukan regularisasi sehingga model dapat mengurangi pengaruh fitur yang kurang relevan sekaligus membantu proses feature selection.
   - **solver = liblinear**  
     Solver yang cocok untuk dataset berukuran kecil hingga menengah serta mendukung regularisasi L1.
   - **class_weight = balanced**  
     Digunakan untuk menangani ketidakseimbangan kelas pada dataset churn sehingga model tidak terlalu bias terhadap kelas mayoritas.
   - **max_iter = 5000**  
     Digunakan untuk memastikan proses optimisasi model mencapai konvergensi.  


3. Evaluasi Model  
     Dalam kasus churn prediction, kesalahan False Negative (FN) memiliki dampak bisnis yang lebih besar dibandingkan False Positive (FP). Hal ini karena pelanggan yang sebenarnya akan churn tetapi tidak terdeteksi oleh model dapat menyebabkan kehilangan pendapatan yang signifikan.  

     Oleh karena itu, evaluasi model difokuskan pada metrik Recall untuk kelas churn.  

     Setelah dilakukan cost-based threshold optimization, diperoleh threshold optimal sebesar 0.10. Dengan threshold ini, model menghasilkan confusion matrix sebagai berikut:  
     • True Negative (TN): 338  
     • False Positive (FP): 697  
     • False Negative (FN): 3  
     • True Positive (TP): 371  

    Berdasarkan hasil tersebut, model menghasilkan performa sebagai berikut:
    • Recall (Churn): 0.992  
    • Precision: 0.347  
    • F1-score: 0.515  

   Nilai recall yang sangat tinggi menunjukkan bahwa hampir seluruh pelanggan yang benar-benar churn berhasil terdeteksi oleh model. Hal ini juga tercermin dari jumlah False Negative yang sangat kecil, yaitu hanya 3 pelanggan churn yang tidak terdeteksi oleh model.  

   Sebagai konsekuensi dari strategi peningkatan recall ini, jumlah False Positive meningkat menjadi 697 pelanggan. Artinya, sebagian pelanggan yang sebenarnya tidak churn ikut terklasifikasi sebagai churn.  

   Namun dalam konteks strategi retensi pelanggan, peningkatan False Positive masih dapat diterima karena biaya pemberian promosi atau program retensi biasanya lebih kecil dibandingkan potensi kehilangan pendapatan akibat pelanggan churn yang tidak terdeteksi.  

   Dengan pendekatan ini, model mampu memaksimalkan deteksi pelanggan berisiko churn sehingga perusahaan dapat melakukan intervensi lebih dini melalui program retensi yang lebih proaktif.

4. Interpretasi Model  
   Salah satu keunggulan Logistic Regression adalah kemampuannya untuk menginterpretasikan pengaruh masing-masing fitur melalui **koefisien model**.  

   Berdasarkan analisis koefisien, beberapa faktor yang paling berkontribusi terhadap kemungkinan churn pelanggan antara lain:  
   - Penggunaan layanan **Fiber Optic**
   - Kontrak **Month-to-Month**
   - Tidak menggunakan layanan tambahan seperti **Online Security** atau **Tech Support**
   - Nilai **Monthly Charges** yang relatif tinggi  

   Sebaliknya, pelanggan dengan kontrak jangka panjang atau yang menggunakan layanan tambahan cenderung memiliki risiko churn yang lebih rendah.  

   Insight ini memberikan informasi yang sangat berharga bagi perusahaan dalam merancang strategi retensi pelanggan yang lebih efektif.  

5. Model Limitation  
   Meskipun model ini memberikan performa yang cukup baik, terdapat beberapa keterbatasan yang perlu diperhatikan.  

   Model hanya dapat digunakan untuk melakukan prediksi pada data yang memiliki **struktur fitur yang sama dengan data training**, yaitu fitur-fitur berikut:

   - gender
   - SeniorCitizen
   - Partner
   - Dependents
   - tenure
   - PhoneService
   - MultipleLines
   - InternetService
   - OnlineSecurity
   - OnlineBackup
   - DeviceProtection
   - TechSupport
   - StreamingTV
   - StreamingMovies
   - Contract
   - PaperlessBilling
   - PaymentMethod
   - MonthlyCharges
   - TotalCharges

   Jika terdapat fitur tambahan atau struktur data yang berbeda, maka model perlu dilatih ulang agar dapat menghasilkan prediksi yang akurat.

   Secara keseluruhan, model churn prediction yang dibangun mampu memberikan insight yang relevan serta dapat digunakan sebagai alat bantu pengambilan keputusan dalam strategi retensi pelanggan.

## Recommendations

Berdasarkan hasil analisis data serta model churn prediction yang telah dibangun, terdapat beberapa rekomendasi strategis yang dapat diterapkan oleh perusahaan untuk mengurangi tingkat churn pelanggan.  

1. Prioritizing High-Risk Customers  
   Model churn prediction dapat digunakan untuk mengidentifikasi pelanggan dengan **probabilitas churn tinggi**. Pelanggan yang termasuk dalam kategori **High Risk** sebaiknya menjadi prioritas utama dalam strategi retensi pelanggan.  
   Tindakan yang dapat dilakukan antara lain:   
   - Memberikan **diskon khusus atau promo personalisasi**
   - Menawarkan **upgrade paket layanan**
   - Memberikan **layanan customer support prioritas**

   Namun demikian, program promosi sebaiknya dilakukan secara **targeted**, misalnya hanya kepada pelanggan dengan probabilitas churn di atas threshold tertentu agar biaya retensi tetap efisien.

2. Improving Fiber Optic Service Quality  
   Hasil interpretasi model menunjukkan bahwa pelanggan dengan layanan **Fiber Optic** memiliki kecenderungan churn yang lebih tinggi.  
   Perusahaan dapat melakukan evaluasi terhadap:  
   - Stabilitas jaringan
   - Kualitas koneksi internet
   - Pengalaman pelanggan dalam menggunakan layanan

   Peningkatan kualitas layanan pada segmen ini berpotensi menurunkan tingkat churn pelanggan secara signifikan.

3. Encouraging Long-Term Contracts  
   Analisis menunjukkan bahwa pelanggan dengan kontrak **Month-to-Month** memiliki risiko churn yang lebih tinggi dibandingkan pelanggan dengan kontrak jangka panjang.  
   Perusahaan dapat mendorong pelanggan untuk beralih ke kontrak tahunan atau dua tahunan melalui:  
   - Program diskon untuk kontrak jangka panjang
   - Bundling layanan tambahan
   - Program loyalitas pelanggan

   Strategi ini tidak hanya mengurangi churn tetapi juga meningkatkan stabilitas pendapatan perusahaan.

4. Implementing Data-Driven Retention Strategy  
   Model churn prediction dapat digunakan sebagai **decision support tool** bagi tim bisnis untuk menentukan strategi retensi pelanggan.  
   Dengan pendekatan berbasis data, perusahaan dapat:  
   - Memprioritaskan pelanggan dengan risiko churn tinggi
   - Mengalokasikan sumber daya retensi secara lebih efisien
   - Mengurangi potensi kehilangan pendapatan akibat churn pelanggan

5. Future Model Improvement  
   Untuk pengembangan lebih lanjut, perusahaan dapat mempertimbangkan beberapa peningkatan, seperti:  
   - Menggunakan model machine learning yang lebih kompleks seperti **Random Forest** atau **Gradient Boosting**
   - Menambahkan fitur tambahan seperti **customer usage pattern** atau **customer interaction data**
   - Mengintegrasikan model ke dalam sistem operasional perusahaan sehingga prediksi churn dapat dilakukan secara **real-time**

---

In [172]:
df_raw = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

output_df = X_test_copy.copy()
output_df.insert(0, "customerID", df_raw.loc[X_test_copy.index, "customerID"].values)

export_df = output_df[[
    "customerID",
    "churn_probability",
    "risk_level",
    "MonthlyCharges",
    "Contract",
    "InternetService"
]]

export_df.to_excel("customer_churn_prediction.xlsx", index=False)
print("File Excel berhasil dibuat")

File Excel berhasil dibuat
